/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// FloatingIPsGetter has a method to return a FloatingIPInterface.
// A group's client should implement this interface.
type FloatingIPsGetter interface {
	FloatingIPs(namespace string) FloatingIPInterface
}

// FloatingIPInterface has methods to work with FloatingIP resources.
type FloatingIPInterface interface {
	Create(ctx context.Context, floatingIP *apiv1alpha1.FloatingIP, opts v1.CreateOptions) (*apiv1alpha1.FloatingIP, error)
	Update(ctx context.Context, floatingIP *apiv1alpha1.FloatingIP, opts v1.UpdateOptions) (*apiv1alpha1.FloatingIP, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, floatingIP *apiv1alpha1.FloatingIP, opts v1.UpdateOptions) (*apiv1alpha1.FloatingIP, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.FloatingIP, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.FloatingIPList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.FloatingIP, err error)
	Apply(ctx context.Context, floatingIP *applyconfigurationapiv1alpha1.FloatingIPApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.FloatingIP, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, floatingIP *applyconfigurationapiv1alpha1.FloatingIPApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.FloatingIP, err error)
	FloatingIPExpansion
}

// floatingIPs implements FloatingIPInterface
type floatingIPs struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.FloatingIP, *apiv1alpha1.FloatingIPList, *applyconfigurationapiv1alpha1.FloatingIPApplyConfiguration]
}

// newFloatingIPs returns a FloatingIPs
func newFloatingIPs(c *OpenstackV1alpha1Client, namespace string) *floatingIPs {
	return &floatingIPs{
		gentype.NewClientWithListAndApply[*apiv1alpha1.FloatingIP, *apiv1alpha1.FloatingIPList, *applyconfigurationapiv1alpha1.FloatingIPApplyConfiguration](
			"floatingips",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.FloatingIP { return &apiv1alpha1.FloatingIP{} },
			func() *apiv1alpha1.FloatingIPList { return &apiv1alpha1.FloatingIPList{} },
		),
	}
}
