/*
Copyright 2025 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// GroupsGetter has a method to return a GroupInterface.
// A group's client should implement this interface.
type GroupsGetter interface {
	Groups(namespace string) GroupInterface
}

// GroupInterface has methods to work with Group resources.
type GroupInterface interface {
	Create(ctx context.Context, group *apiv1alpha1.Group, opts v1.CreateOptions) (*apiv1alpha1.Group, error)
	Update(ctx context.Context, group *apiv1alpha1.Group, opts v1.UpdateOptions) (*apiv1alpha1.Group, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, group *apiv1alpha1.Group, opts v1.UpdateOptions) (*apiv1alpha1.Group, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.Group, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.GroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.Group, err error)
	Apply(ctx context.Context, group *applyconfigurationapiv1alpha1.GroupApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Group, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, group *applyconfigurationapiv1alpha1.GroupApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Group, err error)
	GroupExpansion
}

// groups implements GroupInterface
type groups struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.Group, *apiv1alpha1.GroupList, *applyconfigurationapiv1alpha1.GroupApplyConfiguration]
}

// newGroups returns a Groups
func newGroups(c *OpenstackV1alpha1Client, namespace string) *groups {
	return &groups{
		gentype.NewClientWithListAndApply[*apiv1alpha1.Group, *apiv1alpha1.GroupList, *applyconfigurationapiv1alpha1.GroupApplyConfiguration](
			"groups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.Group { return &apiv1alpha1.Group{} },
			func() *apiv1alpha1.GroupList { return &apiv1alpha1.GroupList{} },
		),
	}
}
