/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// LBPoolsGetter has a method to return a LBPoolInterface.
// A group's client should implement this interface.
type LBPoolsGetter interface {
	LBPools(namespace string) LBPoolInterface
}

// LBPoolInterface has methods to work with LBPool resources.
type LBPoolInterface interface {
	Create(ctx context.Context, lBPool *apiv1alpha1.LBPool, opts v1.CreateOptions) (*apiv1alpha1.LBPool, error)
	Update(ctx context.Context, lBPool *apiv1alpha1.LBPool, opts v1.UpdateOptions) (*apiv1alpha1.LBPool, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, lBPool *apiv1alpha1.LBPool, opts v1.UpdateOptions) (*apiv1alpha1.LBPool, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.LBPool, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.LBPoolList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.LBPool, err error)
	Apply(ctx context.Context, lBPool *applyconfigurationapiv1alpha1.LBPoolApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.LBPool, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, lBPool *applyconfigurationapiv1alpha1.LBPoolApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.LBPool, err error)
	LBPoolExpansion
}

// lBPools implements LBPoolInterface
type lBPools struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.LBPool, *apiv1alpha1.LBPoolList, *applyconfigurationapiv1alpha1.LBPoolApplyConfiguration]
}

// newLBPools returns a LBPools
func newLBPools(c *OpenstackV1alpha1Client, namespace string) *lBPools {
	return &lBPools{
		gentype.NewClientWithListAndApply[*apiv1alpha1.LBPool, *apiv1alpha1.LBPoolList, *applyconfigurationapiv1alpha1.LBPoolApplyConfiguration](
			"lbpools",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.LBPool { return &apiv1alpha1.LBPool{} },
			func() *apiv1alpha1.LBPoolList { return &apiv1alpha1.LBPoolList{} },
		),
	}
}
