/*
Copyright 2025 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ProjectsGetter has a method to return a ProjectInterface.
// A group's client should implement this interface.
type ProjectsGetter interface {
	Projects(namespace string) ProjectInterface
}

// ProjectInterface has methods to work with Project resources.
type ProjectInterface interface {
	Create(ctx context.Context, project *apiv1alpha1.Project, opts v1.CreateOptions) (*apiv1alpha1.Project, error)
	Update(ctx context.Context, project *apiv1alpha1.Project, opts v1.UpdateOptions) (*apiv1alpha1.Project, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, project *apiv1alpha1.Project, opts v1.UpdateOptions) (*apiv1alpha1.Project, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.Project, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ProjectList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.Project, err error)
	Apply(ctx context.Context, project *applyconfigurationapiv1alpha1.ProjectApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Project, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, project *applyconfigurationapiv1alpha1.ProjectApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.Project, err error)
	ProjectExpansion
}

// projects implements ProjectInterface
type projects struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.Project, *apiv1alpha1.ProjectList, *applyconfigurationapiv1alpha1.ProjectApplyConfiguration]
}

// newProjects returns a Projects
func newProjects(c *OpenstackV1alpha1Client, namespace string) *projects {
	return &projects{
		gentype.NewClientWithListAndApply[*apiv1alpha1.Project, *apiv1alpha1.ProjectList, *applyconfigurationapiv1alpha1.ProjectApplyConfiguration](
			"projects",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.Project { return &apiv1alpha1.Project{} },
			func() *apiv1alpha1.ProjectList { return &apiv1alpha1.ProjectList{} },
		),
	}
}
