/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v3/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v3/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v3/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// RecordSetsGetter has a method to return a RecordSetInterface.
// A group's client should implement this interface.
type RecordSetsGetter interface {
	RecordSets(namespace string) RecordSetInterface
}

// RecordSetInterface has methods to work with RecordSet resources.
type RecordSetInterface interface {
	Create(ctx context.Context, recordSet *apiv1alpha1.RecordSet, opts v1.CreateOptions) (*apiv1alpha1.RecordSet, error)
	Update(ctx context.Context, recordSet *apiv1alpha1.RecordSet, opts v1.UpdateOptions) (*apiv1alpha1.RecordSet, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, recordSet *apiv1alpha1.RecordSet, opts v1.UpdateOptions) (*apiv1alpha1.RecordSet, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.RecordSet, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.RecordSetList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.RecordSet, err error)
	Apply(ctx context.Context, recordSet *applyconfigurationapiv1alpha1.RecordSetApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.RecordSet, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, recordSet *applyconfigurationapiv1alpha1.RecordSetApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.RecordSet, err error)
	RecordSetExpansion
}

// recordSets implements RecordSetInterface
type recordSets struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.RecordSet, *apiv1alpha1.RecordSetList, *applyconfigurationapiv1alpha1.RecordSetApplyConfiguration]
}

// newRecordSets returns a RecordSets
func newRecordSets(c *OpenstackV1alpha1Client, namespace string) *recordSets {
	return &recordSets{
		gentype.NewClientWithListAndApply[*apiv1alpha1.RecordSet, *apiv1alpha1.RecordSetList, *applyconfigurationapiv1alpha1.RecordSetApplyConfiguration](
			"recordsets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.RecordSet { return &apiv1alpha1.RecordSet{} },
			func() *apiv1alpha1.RecordSetList { return &apiv1alpha1.RecordSetList{} },
		),
	}
}
