/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServerGroupsGetter has a method to return a ServerGroupInterface.
// A group's client should implement this interface.
type ServerGroupsGetter interface {
	ServerGroups(namespace string) ServerGroupInterface
}

// ServerGroupInterface has methods to work with ServerGroup resources.
type ServerGroupInterface interface {
	Create(ctx context.Context, serverGroup *apiv1alpha1.ServerGroup, opts v1.CreateOptions) (*apiv1alpha1.ServerGroup, error)
	Update(ctx context.Context, serverGroup *apiv1alpha1.ServerGroup, opts v1.UpdateOptions) (*apiv1alpha1.ServerGroup, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serverGroup *apiv1alpha1.ServerGroup, opts v1.UpdateOptions) (*apiv1alpha1.ServerGroup, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ServerGroup, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ServerGroupList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ServerGroup, err error)
	Apply(ctx context.Context, serverGroup *applyconfigurationapiv1alpha1.ServerGroupApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ServerGroup, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, serverGroup *applyconfigurationapiv1alpha1.ServerGroupApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ServerGroup, err error)
	ServerGroupExpansion
}

// serverGroups implements ServerGroupInterface
type serverGroups struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.ServerGroup, *apiv1alpha1.ServerGroupList, *applyconfigurationapiv1alpha1.ServerGroupApplyConfiguration]
}

// newServerGroups returns a ServerGroups
func newServerGroups(c *OpenstackV1alpha1Client, namespace string) *serverGroups {
	return &serverGroups{
		gentype.NewClientWithListAndApply[*apiv1alpha1.ServerGroup, *apiv1alpha1.ServerGroupList, *applyconfigurationapiv1alpha1.ServerGroupApplyConfiguration](
			"servergroups",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.ServerGroup { return &apiv1alpha1.ServerGroup{} },
			func() *apiv1alpha1.ServerGroupList { return &apiv1alpha1.ServerGroupList{} },
		),
	}
}
