/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ShareNetworksGetter has a method to return a ShareNetworkInterface.
// A group's client should implement this interface.
type ShareNetworksGetter interface {
	ShareNetworks(namespace string) ShareNetworkInterface
}

// ShareNetworkInterface has methods to work with ShareNetwork resources.
type ShareNetworkInterface interface {
	Create(ctx context.Context, shareNetwork *apiv1alpha1.ShareNetwork, opts v1.CreateOptions) (*apiv1alpha1.ShareNetwork, error)
	Update(ctx context.Context, shareNetwork *apiv1alpha1.ShareNetwork, opts v1.UpdateOptions) (*apiv1alpha1.ShareNetwork, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, shareNetwork *apiv1alpha1.ShareNetwork, opts v1.UpdateOptions) (*apiv1alpha1.ShareNetwork, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.ShareNetwork, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.ShareNetworkList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.ShareNetwork, err error)
	Apply(ctx context.Context, shareNetwork *applyconfigurationapiv1alpha1.ShareNetworkApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ShareNetwork, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, shareNetwork *applyconfigurationapiv1alpha1.ShareNetworkApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.ShareNetwork, err error)
	ShareNetworkExpansion
}

// shareNetworks implements ShareNetworkInterface
type shareNetworks struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.ShareNetwork, *apiv1alpha1.ShareNetworkList, *applyconfigurationapiv1alpha1.ShareNetworkApplyConfiguration]
}

// newShareNetworks returns a ShareNetworks
func newShareNetworks(c *OpenstackV1alpha1Client, namespace string) *shareNetworks {
	return &shareNetworks{
		gentype.NewClientWithListAndApply[*apiv1alpha1.ShareNetwork, *apiv1alpha1.ShareNetworkList, *applyconfigurationapiv1alpha1.ShareNetworkApplyConfiguration](
			"sharenetworks",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.ShareNetwork { return &apiv1alpha1.ShareNetwork{} },
			func() *apiv1alpha1.ShareNetworkList { return &apiv1alpha1.ShareNetworkList{} },
		),
	}
}
