/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SwiftContainersGetter has a method to return a SwiftContainerInterface.
// A group's client should implement this interface.
type SwiftContainersGetter interface {
	SwiftContainers(namespace string) SwiftContainerInterface
}

// SwiftContainerInterface has methods to work with SwiftContainer resources.
type SwiftContainerInterface interface {
	Create(ctx context.Context, swiftContainer *apiv1alpha1.SwiftContainer, opts v1.CreateOptions) (*apiv1alpha1.SwiftContainer, error)
	Update(ctx context.Context, swiftContainer *apiv1alpha1.SwiftContainer, opts v1.UpdateOptions) (*apiv1alpha1.SwiftContainer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, swiftContainer *apiv1alpha1.SwiftContainer, opts v1.UpdateOptions) (*apiv1alpha1.SwiftContainer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.SwiftContainer, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.SwiftContainerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.SwiftContainer, err error)
	Apply(ctx context.Context, swiftContainer *applyconfigurationapiv1alpha1.SwiftContainerApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.SwiftContainer, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, swiftContainer *applyconfigurationapiv1alpha1.SwiftContainerApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.SwiftContainer, err error)
	SwiftContainerExpansion
}

// swiftContainers implements SwiftContainerInterface
type swiftContainers struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.SwiftContainer, *apiv1alpha1.SwiftContainerList, *applyconfigurationapiv1alpha1.SwiftContainerApplyConfiguration]
}

// newSwiftContainers returns a SwiftContainers
func newSwiftContainers(c *OpenstackV1alpha1Client, namespace string) *swiftContainers {
	return &swiftContainers{
		gentype.NewClientWithListAndApply[*apiv1alpha1.SwiftContainer, *apiv1alpha1.SwiftContainerList, *applyconfigurationapiv1alpha1.SwiftContainerApplyConfiguration](
			"swiftcontainers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.SwiftContainer { return &apiv1alpha1.SwiftContainer{} },
			func() *apiv1alpha1.SwiftContainerList { return &apiv1alpha1.SwiftContainerList{} },
		),
	}
}
