/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VolumeTypesGetter has a method to return a VolumeTypeInterface.
// A group's client should implement this interface.
type VolumeTypesGetter interface {
	VolumeTypes(namespace string) VolumeTypeInterface
}

// VolumeTypeInterface has methods to work with VolumeType resources.
type VolumeTypeInterface interface {
	Create(ctx context.Context, volumeType *apiv1alpha1.VolumeType, opts v1.CreateOptions) (*apiv1alpha1.VolumeType, error)
	Update(ctx context.Context, volumeType *apiv1alpha1.VolumeType, opts v1.UpdateOptions) (*apiv1alpha1.VolumeType, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, volumeType *apiv1alpha1.VolumeType, opts v1.UpdateOptions) (*apiv1alpha1.VolumeType, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.VolumeType, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.VolumeTypeList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.VolumeType, err error)
	Apply(ctx context.Context, volumeType *applyconfigurationapiv1alpha1.VolumeTypeApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.VolumeType, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, volumeType *applyconfigurationapiv1alpha1.VolumeTypeApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.VolumeType, err error)
	VolumeTypeExpansion
}

// volumeTypes implements VolumeTypeInterface
type volumeTypes struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.VolumeType, *apiv1alpha1.VolumeTypeList, *applyconfigurationapiv1alpha1.VolumeTypeApplyConfiguration]
}

// newVolumeTypes returns a VolumeTypes
func newVolumeTypes(c *OpenstackV1alpha1Client, namespace string) *volumeTypes {
	return &volumeTypes{
		gentype.NewClientWithListAndApply[*apiv1alpha1.VolumeType, *apiv1alpha1.VolumeTypeList, *applyconfigurationapiv1alpha1.VolumeTypeApplyConfiguration](
			"volumetypes",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.VolumeType { return &apiv1alpha1.VolumeType{} },
			func() *apiv1alpha1.VolumeTypeList { return &apiv1alpha1.VolumeTypeList{} },
		),
	}
}
