/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	applyconfigurationapiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/applyconfiguration/api/v1alpha1"
	scheme "github.com/k-orc/openstack-resource-controller/v2/pkg/clients/clientset/clientset/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// VolumeSnapshotsGetter has a method to return a VolumeSnapshotInterface.
// A group's client should implement this interface.
type VolumeSnapshotsGetter interface {
	VolumeSnapshots(namespace string) VolumeSnapshotInterface
}

// VolumeSnapshotInterface has methods to work with VolumeSnapshot resources.
type VolumeSnapshotInterface interface {
	Create(ctx context.Context, volumeSnapshot *apiv1alpha1.VolumeSnapshot, opts v1.CreateOptions) (*apiv1alpha1.VolumeSnapshot, error)
	Update(ctx context.Context, volumeSnapshot *apiv1alpha1.VolumeSnapshot, opts v1.UpdateOptions) (*apiv1alpha1.VolumeSnapshot, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, volumeSnapshot *apiv1alpha1.VolumeSnapshot, opts v1.UpdateOptions) (*apiv1alpha1.VolumeSnapshot, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.VolumeSnapshot, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.VolumeSnapshotList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.VolumeSnapshot, err error)
	Apply(ctx context.Context, volumeSnapshot *applyconfigurationapiv1alpha1.VolumeSnapshotApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.VolumeSnapshot, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, volumeSnapshot *applyconfigurationapiv1alpha1.VolumeSnapshotApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.VolumeSnapshot, err error)
	VolumeSnapshotExpansion
}

// volumeSnapshots implements VolumeSnapshotInterface
type volumeSnapshots struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.VolumeSnapshot, *apiv1alpha1.VolumeSnapshotList, *applyconfigurationapiv1alpha1.VolumeSnapshotApplyConfiguration]
}

// newVolumeSnapshots returns a VolumeSnapshots
func newVolumeSnapshots(c *OpenstackV1alpha1Client, namespace string) *volumeSnapshots {
	return &volumeSnapshots{
		gentype.NewClientWithListAndApply[*apiv1alpha1.VolumeSnapshot, *apiv1alpha1.VolumeSnapshotList, *applyconfigurationapiv1alpha1.VolumeSnapshotApplyConfiguration](
			"volumesnapshots",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.VolumeSnapshot { return &apiv1alpha1.VolumeSnapshot{} },
			func() *apiv1alpha1.VolumeSnapshotList { return &apiv1alpha1.VolumeSnapshotList{} },
		),
	}
}
