version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - kubeapilinter
    - lll
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
    custom:
      kubeapilinter:
        type: module
        description: Kube API Linter lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            disable:
              # NOTE: conflicts with the lack of validation in the Status structs
              - arrayofstruct
            enable:
              - commentstart
              - conditions
              - defaults
              - duplicatemarkers
              - integers
              - jsontags
              - maxlength
              # NOTE: we have a number of boolean fields. Should we convert them to
              # string?
              # - nobools
              - nodurations
              - nofloats
              - nomaps
              - nonpointerstructs
              - nonullable
              - notimestamp
              - nophase
              - optionalorrequired
              - requiredfields
              - ssatags
              - statusoptional
              - statussubresource
              - uniquemarkers
          lintersConfig:
            conditions:
              isFirstField: Warn
              usePatchStrategy: Ignore
              useProtobuf: Forbid
            defaults:
              # Let's use `+kubebuilder:default` until elastic/crd-ref-docs supports `+default`
              preferredDefaultMarker: "kubebuilder:default"
            requiredfields:
              omitempty:
                policy: Ignore
  exclusions:
    generated: disable
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
        - dupl
        - goimports
        - unparam
        path: zz_generated
      - linters:
          - kubeapilinter
        path-except: ^api/*
    paths:
      - third_party$
      - builtin$
      - examples$
      - applyconfiguration/*
      - clientset/*
      - informers/*
      - listers/*
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  exclude-generated: disable
