apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackCloud
metadata:
  labels:
    app.kubernetes.io/name: openstackcloud
    app.kubernetes.io/instance: openstackcloud-osp1
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: osp1
spec:
  cloud: devstack
  credentials:
    source: secret
    secretRef:
      name: openstack-clouds
      key: clouds.yaml
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackFlavor
metadata:
  labels:
    app.kubernetes.io/name: openstackflavor
    app.kubernetes.io/instance: openstackflavor-small
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: small
spec:
  cloud: osp1
  id: "1"
  unmanaged: true
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackImage
metadata:
  labels:
    app.kubernetes.io/name: openstackimage
    app.kubernetes.io/instance: openstackimage-fedora
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: fedora
spec:
  cloud: osp1
  resource:
    name: fedora-39
    containerFormat: bare
    diskFormat: qcow2
    method: web-download
    webDownload:
      url: https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackNetwork
metadata:
  labels:
    app.kubernetes.io/name: openstacknetwork
    app.kubernetes.io/instance: openstacknetwork-external
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: external
spec:
  cloud: osp1
  resource:
    name: public
  unmanaged: true
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackNetwork
metadata:
  labels:
    app.kubernetes.io/name: openstacknetwork
    app.kubernetes.io/instance: openstacknetwork-network-1
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: network-1
spec:
  cloud: osp1
  resource:
    name: simple-server-network
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSubnet
metadata:
  labels:
    app.kubernetes.io/name: openstacksubnet
    app.kubernetes.io/instance: openstacksubnet-subnet-1
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: subnet-1
spec:
  cloud: osp1
  resource:
    name: subnet-1
    network: network-1
    allocationPools:
    - start: 192.168.1.5
      end: 192.168.1.60
    cidr: 192.168.1.0/24
    ipVersion: IPv4
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackPort
metadata:
  labels:
    app.kubernetes.io/name: openstackport
    app.kubernetes.io/instance: openstackport-port-1
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: port-1
spec:
  cloud: osp1
  resource:
    name: port-1
    network: network-1
    securityGroups:
      - workstation
    fixedIPs:
      - subnet: subnet-1
        ipAddress: 192.168.1.55
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackServer
metadata:
  labels:
    app.kubernetes.io/name: openstackserver
    app.kubernetes.io/instance: openstackserver-workstation
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: workstation
spec:
  cloud: osp1
  resource:
    name: workstation
    image: fedora
    flavor: small
    networks:
    - port: port-1
    securityGroups:
    - workstation
    key: mykey
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackFloatingIP
metadata:
  labels:
    app.kubernetes.io/name: openstackfloatingip
    app.kubernetes.io/instance: openstackfloatingip-fip-1
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: fip-1
spec:
  cloud: osp1
  resource:
    description: Provisioned by openstack-resource-controller
    floatingNetwork: external
    port: port-1
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackRouter
metadata:
  labels:
    app.kubernetes.io/name: openstackrouter
    app.kubernetes.io/instance: openstackrouter-router-1
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: router-1
spec:
  cloud: osp1
  resource:
    name: router-1
    externalGatewayInfo:
      network: external
    ports:
      - port-2
    description: 'provisioned by ORC'
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackPort
metadata:
  labels:
    app.kubernetes.io/name: openstackport
    app.kubernetes.io/instance: openstackport-port-2
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: port-2
spec:
  cloud: osp1
  resource:
    name: port-2
    network: network-1
    securityGroups:
      - workstation
    fixedIPs:
      - subnet: subnet-1
        ipAddress: 192.168.1.1
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroup
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygroup
    app.kubernetes.io/instance: openstacksecuritygroup-ssh
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: workstation
spec:
  cloud: osp1
  resource:
    name: workstation
    description: 'For ping and access with SSH and mosh'
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-ssh-ipv4
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: ssh-ipv4
spec:
  cloud: osp1
  resource:
    securityGroup: workstation
    direction: ingress
    description: ssh
    portRangeMin: 22
    portRangeMax: 22
    protocol: TCP
    etherType: IPv4
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-mosh-ipv4
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: mosh-ipv4
spec:
  cloud: osp1
  resource:
    securityGroup: workstation
    direction: ingress
    description: mosh
    portRangeMin: 60000
    portRangeMax: 61000
    protocol: UDP
    etherType: IPv4
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-ssh-ipv6
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: ssh-ipv6
spec:
  cloud: osp1
  resource:
    securityGroup: workstation
    direction: ingress
    description: ssh
    portRangeMin: 22
    portRangeMax: 22
    protocol: TCP
    etherType: IPv6
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-mosh-ipv6
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: mosh-ipv6
spec:
  cloud: osp1
  resource:
    securityGroup: workstation
    direction: ingress
    description: mosh
    portRangeMin: 60000
    portRangeMax: 61000
    protocol: UDP
    etherType: IPv6
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-ping-ipv4
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: ping-ipv4
spec:
  cloud: osp1
  resource:
    securityGroup: workstation
    direction: ingress
    description: ping
    protocol: ICMP
    etherType: IPv4
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-ping-ipv6
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: ping-ipv6
spec:
  cloud: osp1
  resource:
    securityGroup: workstation
    direction: ingress
    description: ping
    protocol: ICMP
    etherType: IPv6
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackKeypair
metadata:
  labels:
    app.kubernetes.io/name: openstackkeypair
    app.kubernetes.io/instance: openstackkeypair-mykey
    app.kubernetes.io/part-of: simple-server
    app.kubernetes.io/managed-by: kustomize
  name: mykey
spec:
  cloud: osp1
  resource:
    name: mykey
    publicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFlYK/koCWHk203WOT8tA8PQtUx1ox+bJZMt9wQrcAa+'
