/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../dns.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=dns.go -source=../dns.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock DNSClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	recordsets "github.com/gophercloud/gophercloud/v2/openstack/dns/v2/recordsets"
	zones "github.com/gophercloud/gophercloud/v2/openstack/dns/v2/zones"
	gomock "go.uber.org/mock/gomock"
)

// MockDNSClient is a mock of DNSClient interface.
type MockDNSClient struct {
	ctrl     *gomock.Controller
	recorder *MockDNSClientMockRecorder
	isgomock struct{}
}

// MockDNSClientMockRecorder is the mock recorder for MockDNSClient.
type MockDNSClientMockRecorder struct {
	mock *MockDNSClient
}

// NewMockDNSClient creates a new mock instance.
func NewMockDNSClient(ctrl *gomock.Controller) *MockDNSClient {
	mock := &MockDNSClient{ctrl: ctrl}
	mock.recorder = &MockDNSClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSClient) EXPECT() *MockDNSClientMockRecorder {
	return m.recorder
}

// CreateRecordSet mocks base method.
func (m *MockDNSClient) CreateRecordSet(ctx context.Context, zoneID string, opts recordsets.CreateOptsBuilder) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordSet", ctx, zoneID, opts)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecordSet indicates an expected call of CreateRecordSet.
func (mr *MockDNSClientMockRecorder) CreateRecordSet(ctx, zoneID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordSet", reflect.TypeOf((*MockDNSClient)(nil).CreateRecordSet), ctx, zoneID, opts)
}

// CreateZone mocks base method.
func (m *MockDNSClient) CreateZone(ctx context.Context, opts zones.CreateOptsBuilder) (*zones.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZone", ctx, opts)
	ret0, _ := ret[0].(*zones.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateZone indicates an expected call of CreateZone.
func (mr *MockDNSClientMockRecorder) CreateZone(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZone", reflect.TypeOf((*MockDNSClient)(nil).CreateZone), ctx, opts)
}

// CreateZoneShare mocks base method.
func (m *MockDNSClient) CreateZoneShare(ctx context.Context, zoneID string, opts zones.ShareOptsBuilder) (*zones.ZoneShare, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZoneShare", ctx, zoneID, opts)
	ret0, _ := ret[0].(*zones.ZoneShare)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateZoneShare indicates an expected call of CreateZoneShare.
func (mr *MockDNSClientMockRecorder) CreateZoneShare(ctx, zoneID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZoneShare", reflect.TypeOf((*MockDNSClient)(nil).CreateZoneShare), ctx, zoneID, opts)
}

// DeleteRecordSet mocks base method.
func (m *MockDNSClient) DeleteRecordSet(ctx context.Context, zoneID, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSet", ctx, zoneID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordSet indicates an expected call of DeleteRecordSet.
func (mr *MockDNSClientMockRecorder) DeleteRecordSet(ctx, zoneID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSet", reflect.TypeOf((*MockDNSClient)(nil).DeleteRecordSet), ctx, zoneID, id)
}

// DeleteZone mocks base method.
func (m *MockDNSClient) DeleteZone(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZone", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteZone indicates an expected call of DeleteZone.
func (mr *MockDNSClientMockRecorder) DeleteZone(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZone", reflect.TypeOf((*MockDNSClient)(nil).DeleteZone), ctx, id)
}

// DeleteZoneShare mocks base method.
func (m *MockDNSClient) DeleteZoneShare(ctx context.Context, zoneID, shareID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZoneShare", ctx, zoneID, shareID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteZoneShare indicates an expected call of DeleteZoneShare.
func (mr *MockDNSClientMockRecorder) DeleteZoneShare(ctx, zoneID, shareID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZoneShare", reflect.TypeOf((*MockDNSClient)(nil).DeleteZoneShare), ctx, zoneID, shareID)
}

// GetRecordSet mocks base method.
func (m *MockDNSClient) GetRecordSet(ctx context.Context, zoneID, id string) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordSet", ctx, zoneID, id)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordSet indicates an expected call of GetRecordSet.
func (mr *MockDNSClientMockRecorder) GetRecordSet(ctx, zoneID, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordSet", reflect.TypeOf((*MockDNSClient)(nil).GetRecordSet), ctx, zoneID, id)
}

// GetZone mocks base method.
func (m *MockDNSClient) GetZone(ctx context.Context, id string) (*zones.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZone", ctx, id)
	ret0, _ := ret[0].(*zones.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZone indicates an expected call of GetZone.
func (mr *MockDNSClientMockRecorder) GetZone(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZone", reflect.TypeOf((*MockDNSClient)(nil).GetZone), ctx, id)
}

// GetZoneShare mocks base method.
func (m *MockDNSClient) GetZoneShare(ctx context.Context, zoneID, shareID string) (*zones.ZoneShare, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneShare", ctx, zoneID, shareID)
	ret0, _ := ret[0].(*zones.ZoneShare)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneShare indicates an expected call of GetZoneShare.
func (mr *MockDNSClientMockRecorder) GetZoneShare(ctx, zoneID, shareID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneShare", reflect.TypeOf((*MockDNSClient)(nil).GetZoneShare), ctx, zoneID, shareID)
}

// ListRecordSets mocks base method.
func (m *MockDNSClient) ListRecordSets(ctx context.Context, zoneID string, listOpts recordsets.ListOptsBuilder) iter.Seq2[*recordsets.RecordSet, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordSets", ctx, zoneID, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*recordsets.RecordSet, error])
	return ret0
}

// ListRecordSets indicates an expected call of ListRecordSets.
func (mr *MockDNSClientMockRecorder) ListRecordSets(ctx, zoneID, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordSets", reflect.TypeOf((*MockDNSClient)(nil).ListRecordSets), ctx, zoneID, listOpts)
}

// ListZoneShares mocks base method.
func (m *MockDNSClient) ListZoneShares(ctx context.Context, zoneID string) iter.Seq2[*zones.ZoneShare, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZoneShares", ctx, zoneID)
	ret0, _ := ret[0].(iter.Seq2[*zones.ZoneShare, error])
	return ret0
}

// ListZoneShares indicates an expected call of ListZoneShares.
func (mr *MockDNSClientMockRecorder) ListZoneShares(ctx, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZoneShares", reflect.TypeOf((*MockDNSClient)(nil).ListZoneShares), ctx, zoneID)
}

// ListZones mocks base method.
func (m *MockDNSClient) ListZones(ctx context.Context, listOpts zones.ListOptsBuilder) iter.Seq2[*zones.Zone, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZones", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*zones.Zone, error])
	return ret0
}

// ListZones indicates an expected call of ListZones.
func (mr *MockDNSClientMockRecorder) ListZones(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZones", reflect.TypeOf((*MockDNSClient)(nil).ListZones), ctx, listOpts)
}

// UpdateRecordSet mocks base method.
func (m *MockDNSClient) UpdateRecordSet(ctx context.Context, zoneID, id string, opts recordsets.UpdateOptsBuilder) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecordSet", ctx, zoneID, id, opts)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecordSet indicates an expected call of UpdateRecordSet.
func (mr *MockDNSClientMockRecorder) UpdateRecordSet(ctx, zoneID, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecordSet", reflect.TypeOf((*MockDNSClient)(nil).UpdateRecordSet), ctx, zoneID, id, opts)
}

// UpdateZone mocks base method.
func (m *MockDNSClient) UpdateZone(ctx context.Context, id string, opts zones.UpdateOptsBuilder) (*zones.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateZone", ctx, id, opts)
	ret0, _ := ret[0].(*zones.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateZone indicates an expected call of UpdateZone.
func (mr *MockDNSClientMockRecorder) UpdateZone(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateZone", reflect.TypeOf((*MockDNSClient)(nil).UpdateZone), ctx, id, opts)
}
