/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../dnszoneshare.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=dnszoneshare.go -source=../dnszoneshare.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock DNSZoneShareClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	zones "github.com/gophercloud/gophercloud/v2/openstack/dns/v2/zones"
	gomock "go.uber.org/mock/gomock"
)

// MockDNSZoneShareClient is a mock of DNSZoneShareClient interface.
type MockDNSZoneShareClient struct {
	ctrl     *gomock.Controller
	recorder *MockDNSZoneShareClientMockRecorder
	isgomock struct{}
}

// MockDNSZoneShareClientMockRecorder is the mock recorder for MockDNSZoneShareClient.
type MockDNSZoneShareClientMockRecorder struct {
	mock *MockDNSZoneShareClient
}

// NewMockDNSZoneShareClient creates a new mock instance.
func NewMockDNSZoneShareClient(ctrl *gomock.Controller) *MockDNSZoneShareClient {
	mock := &MockDNSZoneShareClient{ctrl: ctrl}
	mock.recorder = &MockDNSZoneShareClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDNSZoneShareClient) EXPECT() *MockDNSZoneShareClientMockRecorder {
	return m.recorder
}

// CreateZoneShare mocks base method.
func (m *MockDNSZoneShareClient) CreateZoneShare(ctx context.Context, zoneID string, opts zones.ShareOptsBuilder) (*zones.ZoneShare, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateZoneShare", ctx, zoneID, opts)
	ret0, _ := ret[0].(*zones.ZoneShare)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateZoneShare indicates an expected call of CreateZoneShare.
func (mr *MockDNSZoneShareClientMockRecorder) CreateZoneShare(ctx, zoneID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateZoneShare", reflect.TypeOf((*MockDNSZoneShareClient)(nil).CreateZoneShare), ctx, zoneID, opts)
}

// DeleteZoneShare mocks base method.
func (m *MockDNSZoneShareClient) DeleteZoneShare(ctx context.Context, zoneID, shareID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteZoneShare", ctx, zoneID, shareID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteZoneShare indicates an expected call of DeleteZoneShare.
func (mr *MockDNSZoneShareClientMockRecorder) DeleteZoneShare(ctx, zoneID, shareID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteZoneShare", reflect.TypeOf((*MockDNSZoneShareClient)(nil).DeleteZoneShare), ctx, zoneID, shareID)
}

// GetZoneShare mocks base method.
func (m *MockDNSZoneShareClient) GetZoneShare(ctx context.Context, zoneID, shareID string) (*zones.ZoneShare, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetZoneShare", ctx, zoneID, shareID)
	ret0, _ := ret[0].(*zones.ZoneShare)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetZoneShare indicates an expected call of GetZoneShare.
func (mr *MockDNSZoneShareClientMockRecorder) GetZoneShare(ctx, zoneID, shareID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetZoneShare", reflect.TypeOf((*MockDNSZoneShareClient)(nil).GetZoneShare), ctx, zoneID, shareID)
}

// ListZoneShares mocks base method.
func (m *MockDNSZoneShareClient) ListZoneShares(ctx context.Context, zoneID string) iter.Seq2[*zones.ZoneShare, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListZoneShares", ctx, zoneID)
	ret0, _ := ret[0].(iter.Seq2[*zones.ZoneShare, error])
	return ret0
}

// ListZoneShares indicates an expected call of ListZoneShares.
func (mr *MockDNSZoneShareClientMockRecorder) ListZoneShares(ctx, zoneID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListZoneShares", reflect.TypeOf((*MockDNSZoneShareClient)(nil).ListZoneShares), ctx, zoneID)
}
