/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../lbpool.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=lbpool.go -source=../lbpool.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock LBPoolClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	pools "github.com/gophercloud/gophercloud/v2/openstack/loadbalancer/v2/pools"
	gomock "go.uber.org/mock/gomock"
)

// MockLBPoolClient is a mock of LBPoolClient interface.
type MockLBPoolClient struct {
	ctrl     *gomock.Controller
	recorder *MockLBPoolClientMockRecorder
	isgomock struct{}
}

// MockLBPoolClientMockRecorder is the mock recorder for MockLBPoolClient.
type MockLBPoolClientMockRecorder struct {
	mock *MockLBPoolClient
}

// NewMockLBPoolClient creates a new mock instance.
func NewMockLBPoolClient(ctrl *gomock.Controller) *MockLBPoolClient {
	mock := &MockLBPoolClient{ctrl: ctrl}
	mock.recorder = &MockLBPoolClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLBPoolClient) EXPECT() *MockLBPoolClientMockRecorder {
	return m.recorder
}

// CreateLBPool mocks base method.
func (m *MockLBPoolClient) CreateLBPool(ctx context.Context, opts pools.CreateOptsBuilder) (*pools.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLBPool", ctx, opts)
	ret0, _ := ret[0].(*pools.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLBPool indicates an expected call of CreateLBPool.
func (mr *MockLBPoolClientMockRecorder) CreateLBPool(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLBPool", reflect.TypeOf((*MockLBPoolClient)(nil).CreateLBPool), ctx, opts)
}

// CreateMember mocks base method.
func (m *MockLBPoolClient) CreateMember(ctx context.Context, poolID string, opts pools.CreateMemberOptsBuilder) (*pools.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMember", ctx, poolID, opts)
	ret0, _ := ret[0].(*pools.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMember indicates an expected call of CreateMember.
func (mr *MockLBPoolClientMockRecorder) CreateMember(ctx, poolID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMember", reflect.TypeOf((*MockLBPoolClient)(nil).CreateMember), ctx, poolID, opts)
}

// DeleteLBPool mocks base method.
func (m *MockLBPoolClient) DeleteLBPool(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLBPool", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLBPool indicates an expected call of DeleteLBPool.
func (mr *MockLBPoolClientMockRecorder) DeleteLBPool(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLBPool", reflect.TypeOf((*MockLBPoolClient)(nil).DeleteLBPool), ctx, resourceID)
}

// DeleteMember mocks base method.
func (m *MockLBPoolClient) DeleteMember(ctx context.Context, poolID, memberID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMember", ctx, poolID, memberID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMember indicates an expected call of DeleteMember.
func (mr *MockLBPoolClientMockRecorder) DeleteMember(ctx, poolID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMember", reflect.TypeOf((*MockLBPoolClient)(nil).DeleteMember), ctx, poolID, memberID)
}

// GetLBPool mocks base method.
func (m *MockLBPoolClient) GetLBPool(ctx context.Context, resourceID string) (*pools.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLBPool", ctx, resourceID)
	ret0, _ := ret[0].(*pools.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLBPool indicates an expected call of GetLBPool.
func (mr *MockLBPoolClientMockRecorder) GetLBPool(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLBPool", reflect.TypeOf((*MockLBPoolClient)(nil).GetLBPool), ctx, resourceID)
}

// GetMember mocks base method.
func (m *MockLBPoolClient) GetMember(ctx context.Context, poolID, memberID string) (*pools.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, poolID, memberID)
	ret0, _ := ret[0].(*pools.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockLBPoolClientMockRecorder) GetMember(ctx, poolID, memberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockLBPoolClient)(nil).GetMember), ctx, poolID, memberID)
}

// ListLBPools mocks base method.
func (m *MockLBPoolClient) ListLBPools(ctx context.Context, listOpts pools.ListOptsBuilder) iter.Seq2[*pools.Pool, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLBPools", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*pools.Pool, error])
	return ret0
}

// ListLBPools indicates an expected call of ListLBPools.
func (mr *MockLBPoolClientMockRecorder) ListLBPools(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLBPools", reflect.TypeOf((*MockLBPoolClient)(nil).ListLBPools), ctx, listOpts)
}

// ListMembers mocks base method.
func (m *MockLBPoolClient) ListMembers(ctx context.Context, poolID string, opts pools.ListMembersOptsBuilder) iter.Seq2[*pools.Member, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, poolID, opts)
	ret0, _ := ret[0].(iter.Seq2[*pools.Member, error])
	return ret0
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockLBPoolClientMockRecorder) ListMembers(ctx, poolID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockLBPoolClient)(nil).ListMembers), ctx, poolID, opts)
}

// UpdateLBPool mocks base method.
func (m *MockLBPoolClient) UpdateLBPool(ctx context.Context, id string, opts pools.UpdateOptsBuilder) (*pools.Pool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLBPool", ctx, id, opts)
	ret0, _ := ret[0].(*pools.Pool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLBPool indicates an expected call of UpdateLBPool.
func (mr *MockLBPoolClientMockRecorder) UpdateLBPool(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLBPool", reflect.TypeOf((*MockLBPoolClient)(nil).UpdateLBPool), ctx, id, opts)
}

// UpdateMember mocks base method.
func (m *MockLBPoolClient) UpdateMember(ctx context.Context, poolID, memberID string, opts pools.UpdateMemberOptsBuilder) (*pools.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMember", ctx, poolID, memberID, opts)
	ret0, _ := ret[0].(*pools.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMember indicates an expected call of UpdateMember.
func (mr *MockLBPoolClientMockRecorder) UpdateMember(ctx, poolID, memberID, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMember", reflect.TypeOf((*MockLBPoolClient)(nil).UpdateMember), ctx, poolID, memberID, opts)
}
