/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../limit.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=limit.go -source=../limit.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock LimitClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	limits "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/limits"
	gomock "go.uber.org/mock/gomock"
)

// MockLimitClient is a mock of LimitClient interface.
type MockLimitClient struct {
	ctrl     *gomock.Controller
	recorder *MockLimitClientMockRecorder
	isgomock struct{}
}

// MockLimitClientMockRecorder is the mock recorder for MockLimitClient.
type MockLimitClientMockRecorder struct {
	mock *MockLimitClient
}

// NewMockLimitClient creates a new mock instance.
func NewMockLimitClient(ctrl *gomock.Controller) *MockLimitClient {
	mock := &MockLimitClient{ctrl: ctrl}
	mock.recorder = &MockLimitClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitClient) EXPECT() *MockLimitClientMockRecorder {
	return m.recorder
}

// CreateLimit mocks base method.
func (m *MockLimitClient) CreateLimit(ctx context.Context, opts limits.BatchCreateOptsBuilder) (*limits.Limit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLimit", ctx, opts)
	ret0, _ := ret[0].(*limits.Limit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLimit indicates an expected call of CreateLimit.
func (mr *MockLimitClientMockRecorder) CreateLimit(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLimit", reflect.TypeOf((*MockLimitClient)(nil).CreateLimit), ctx, opts)
}

// DeleteLimit mocks base method.
func (m *MockLimitClient) DeleteLimit(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLimit", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLimit indicates an expected call of DeleteLimit.
func (mr *MockLimitClientMockRecorder) DeleteLimit(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLimit", reflect.TypeOf((*MockLimitClient)(nil).DeleteLimit), ctx, resourceID)
}

// GetLimit mocks base method.
func (m *MockLimitClient) GetLimit(ctx context.Context, resourceID string) (*limits.Limit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimit", ctx, resourceID)
	ret0, _ := ret[0].(*limits.Limit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimit indicates an expected call of GetLimit.
func (mr *MockLimitClientMockRecorder) GetLimit(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimit", reflect.TypeOf((*MockLimitClient)(nil).GetLimit), ctx, resourceID)
}

// ListLimits mocks base method.
func (m *MockLimitClient) ListLimits(ctx context.Context, listOpts limits.ListOptsBuilder) iter.Seq2[*limits.Limit, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLimits", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*limits.Limit, error])
	return ret0
}

// ListLimits indicates an expected call of ListLimits.
func (mr *MockLimitClientMockRecorder) ListLimits(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLimits", reflect.TypeOf((*MockLimitClient)(nil).ListLimits), ctx, listOpts)
}

// UpdateLimit mocks base method.
func (m *MockLimitClient) UpdateLimit(ctx context.Context, id string, opts limits.UpdateOptsBuilder) (*limits.Limit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLimit", ctx, id, opts)
	ret0, _ := ret[0].(*limits.Limit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateLimit indicates an expected call of UpdateLimit.
func (mr *MockLimitClientMockRecorder) UpdateLimit(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLimit", reflect.TypeOf((*MockLimitClient)(nil).UpdateLimit), ctx, id, opts)
}
