/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../listener.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=listener.go -source=../listener.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock ListenerClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	listeners "github.com/gophercloud/gophercloud/v2/openstack/loadbalancer/v2/listeners"
	gomock "go.uber.org/mock/gomock"
)

// MockListenerClient is a mock of ListenerClient interface.
type MockListenerClient struct {
	ctrl     *gomock.Controller
	recorder *MockListenerClientMockRecorder
	isgomock struct{}
}

// MockListenerClientMockRecorder is the mock recorder for MockListenerClient.
type MockListenerClientMockRecorder struct {
	mock *MockListenerClient
}

// NewMockListenerClient creates a new mock instance.
func NewMockListenerClient(ctrl *gomock.Controller) *MockListenerClient {
	mock := &MockListenerClient{ctrl: ctrl}
	mock.recorder = &MockListenerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenerClient) EXPECT() *MockListenerClientMockRecorder {
	return m.recorder
}

// CreateListener mocks base method.
func (m *MockListenerClient) CreateListener(ctx context.Context, opts listeners.CreateOptsBuilder) (*listeners.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateListener", ctx, opts)
	ret0, _ := ret[0].(*listeners.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateListener indicates an expected call of CreateListener.
func (mr *MockListenerClientMockRecorder) CreateListener(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateListener", reflect.TypeOf((*MockListenerClient)(nil).CreateListener), ctx, opts)
}

// DeleteListener mocks base method.
func (m *MockListenerClient) DeleteListener(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteListener", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteListener indicates an expected call of DeleteListener.
func (mr *MockListenerClientMockRecorder) DeleteListener(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteListener", reflect.TypeOf((*MockListenerClient)(nil).DeleteListener), ctx, resourceID)
}

// GetListener mocks base method.
func (m *MockListenerClient) GetListener(ctx context.Context, resourceID string) (*listeners.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetListener", ctx, resourceID)
	ret0, _ := ret[0].(*listeners.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetListener indicates an expected call of GetListener.
func (mr *MockListenerClientMockRecorder) GetListener(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetListener", reflect.TypeOf((*MockListenerClient)(nil).GetListener), ctx, resourceID)
}

// ListListeners mocks base method.
func (m *MockListenerClient) ListListeners(ctx context.Context, listOpts listeners.ListOptsBuilder) iter.Seq2[*listeners.Listener, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListListeners", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*listeners.Listener, error])
	return ret0
}

// ListListeners indicates an expected call of ListListeners.
func (mr *MockListenerClientMockRecorder) ListListeners(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListListeners", reflect.TypeOf((*MockListenerClient)(nil).ListListeners), ctx, listOpts)
}

// UpdateListener mocks base method.
func (m *MockListenerClient) UpdateListener(ctx context.Context, id string, opts listeners.UpdateOptsBuilder) (*listeners.Listener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateListener", ctx, id, opts)
	ret0, _ := ret[0].(*listeners.Listener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateListener indicates an expected call of UpdateListener.
func (mr *MockListenerClientMockRecorder) UpdateListener(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateListener", reflect.TypeOf((*MockListenerClient)(nil).UpdateListener), ctx, id, opts)
}
