/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../recordset.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=recordset.go -source=../recordset.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock RecordSetClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	recordsets "github.com/gophercloud/gophercloud/v2/openstack/dns/v2/recordsets"
	gomock "go.uber.org/mock/gomock"
)

// MockRecordSetClient is a mock of RecordSetClient interface.
type MockRecordSetClient struct {
	ctrl     *gomock.Controller
	recorder *MockRecordSetClientMockRecorder
	isgomock struct{}
}

// MockRecordSetClientMockRecorder is the mock recorder for MockRecordSetClient.
type MockRecordSetClientMockRecorder struct {
	mock *MockRecordSetClient
}

// NewMockRecordSetClient creates a new mock instance.
func NewMockRecordSetClient(ctrl *gomock.Controller) *MockRecordSetClient {
	mock := &MockRecordSetClient{ctrl: ctrl}
	mock.recorder = &MockRecordSetClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecordSetClient) EXPECT() *MockRecordSetClientMockRecorder {
	return m.recorder
}

// CreateRecordSet mocks base method.
func (m *MockRecordSetClient) CreateRecordSet(ctx context.Context, opts recordsets.CreateOptsBuilder) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRecordSet", ctx, opts)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRecordSet indicates an expected call of CreateRecordSet.
func (mr *MockRecordSetClientMockRecorder) CreateRecordSet(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRecordSet", reflect.TypeOf((*MockRecordSetClient)(nil).CreateRecordSet), ctx, opts)
}

// DeleteRecordSet mocks base method.
func (m *MockRecordSetClient) DeleteRecordSet(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRecordSet", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRecordSet indicates an expected call of DeleteRecordSet.
func (mr *MockRecordSetClientMockRecorder) DeleteRecordSet(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRecordSet", reflect.TypeOf((*MockRecordSetClient)(nil).DeleteRecordSet), ctx, resourceID)
}

// GetRecordSet mocks base method.
func (m *MockRecordSetClient) GetRecordSet(ctx context.Context, resourceID string) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecordSet", ctx, resourceID)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecordSet indicates an expected call of GetRecordSet.
func (mr *MockRecordSetClientMockRecorder) GetRecordSet(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecordSet", reflect.TypeOf((*MockRecordSetClient)(nil).GetRecordSet), ctx, resourceID)
}

// ListRecordSets mocks base method.
func (m *MockRecordSetClient) ListRecordSets(ctx context.Context, listOpts recordsets.ListOptsBuilder) iter.Seq2[*recordsets.RecordSet, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecordSets", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*recordsets.RecordSet, error])
	return ret0
}

// ListRecordSets indicates an expected call of ListRecordSets.
func (mr *MockRecordSetClientMockRecorder) ListRecordSets(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecordSets", reflect.TypeOf((*MockRecordSetClient)(nil).ListRecordSets), ctx, listOpts)
}

// UpdateRecordSet mocks base method.
func (m *MockRecordSetClient) UpdateRecordSet(ctx context.Context, id string, opts recordsets.UpdateOptsBuilder) (*recordsets.RecordSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecordSet", ctx, id, opts)
	ret0, _ := ret[0].(*recordsets.RecordSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRecordSet indicates an expected call of UpdateRecordSet.
func (mr *MockRecordSetClientMockRecorder) UpdateRecordSet(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecordSet", reflect.TypeOf((*MockRecordSetClient)(nil).UpdateRecordSet), ctx, id, opts)
}
