/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../region.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=region.go -source=../region.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock RegionClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	regions "github.com/gophercloud/gophercloud/v2/openstack/identity/v3/regions"
	gomock "go.uber.org/mock/gomock"
)

// MockRegionClient is a mock of RegionClient interface.
type MockRegionClient struct {
	ctrl     *gomock.Controller
	recorder *MockRegionClientMockRecorder
	isgomock struct{}
}

// MockRegionClientMockRecorder is the mock recorder for MockRegionClient.
type MockRegionClientMockRecorder struct {
	mock *MockRegionClient
}

// NewMockRegionClient creates a new mock instance.
func NewMockRegionClient(ctrl *gomock.Controller) *MockRegionClient {
	mock := &MockRegionClient{ctrl: ctrl}
	mock.recorder = &MockRegionClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionClient) EXPECT() *MockRegionClientMockRecorder {
	return m.recorder
}

// CreateRegion mocks base method.
func (m *MockRegionClient) CreateRegion(ctx context.Context, opts regions.CreateOptsBuilder) (*regions.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRegion", ctx, opts)
	ret0, _ := ret[0].(*regions.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRegion indicates an expected call of CreateRegion.
func (mr *MockRegionClientMockRecorder) CreateRegion(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRegion", reflect.TypeOf((*MockRegionClient)(nil).CreateRegion), ctx, opts)
}

// DeleteRegion mocks base method.
func (m *MockRegionClient) DeleteRegion(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRegion", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRegion indicates an expected call of DeleteRegion.
func (mr *MockRegionClientMockRecorder) DeleteRegion(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRegion", reflect.TypeOf((*MockRegionClient)(nil).DeleteRegion), ctx, resourceID)
}

// GetRegion mocks base method.
func (m *MockRegionClient) GetRegion(ctx context.Context, resourceID string) (*regions.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRegion", ctx, resourceID)
	ret0, _ := ret[0].(*regions.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRegion indicates an expected call of GetRegion.
func (mr *MockRegionClientMockRecorder) GetRegion(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRegion", reflect.TypeOf((*MockRegionClient)(nil).GetRegion), ctx, resourceID)
}

// ListRegions mocks base method.
func (m *MockRegionClient) ListRegions(ctx context.Context, listOpts regions.ListOptsBuilder) iter.Seq2[*regions.Region, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRegions", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*regions.Region, error])
	return ret0
}

// ListRegions indicates an expected call of ListRegions.
func (mr *MockRegionClientMockRecorder) ListRegions(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRegions", reflect.TypeOf((*MockRegionClient)(nil).ListRegions), ctx, listOpts)
}

// UpdateRegion mocks base method.
func (m *MockRegionClient) UpdateRegion(ctx context.Context, id string, opts regions.UpdateOptsBuilder) (*regions.Region, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRegion", ctx, id, opts)
	ret0, _ := ret[0].(*regions.Region)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRegion indicates an expected call of UpdateRegion.
func (mr *MockRegionClientMockRecorder) UpdateRegion(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRegion", reflect.TypeOf((*MockRegionClient)(nil).UpdateRegion), ctx, id, opts)
}
