/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../share.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=share.go -source=../share.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock ShareClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	shares "github.com/gophercloud/gophercloud/v2/openstack/sharedfilesystems/v2/shares"
	gomock "go.uber.org/mock/gomock"
)

// MockShareClient is a mock of ShareClient interface.
type MockShareClient struct {
	ctrl     *gomock.Controller
	recorder *MockShareClientMockRecorder
	isgomock struct{}
}

// MockShareClientMockRecorder is the mock recorder for MockShareClient.
type MockShareClientMockRecorder struct {
	mock *MockShareClient
}

// NewMockShareClient creates a new mock instance.
func NewMockShareClient(ctrl *gomock.Controller) *MockShareClient {
	mock := &MockShareClient{ctrl: ctrl}
	mock.recorder = &MockShareClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShareClient) EXPECT() *MockShareClientMockRecorder {
	return m.recorder
}

// CreateShare mocks base method.
func (m *MockShareClient) CreateShare(ctx context.Context, opts shares.CreateOptsBuilder) (*shares.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShare", ctx, opts)
	ret0, _ := ret[0].(*shares.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShare indicates an expected call of CreateShare.
func (mr *MockShareClientMockRecorder) CreateShare(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShare", reflect.TypeOf((*MockShareClient)(nil).CreateShare), ctx, opts)
}

// DeleteShare mocks base method.
func (m *MockShareClient) DeleteShare(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteShare", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteShare indicates an expected call of DeleteShare.
func (mr *MockShareClientMockRecorder) DeleteShare(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteShare", reflect.TypeOf((*MockShareClient)(nil).DeleteShare), ctx, resourceID)
}

// GetShare mocks base method.
func (m *MockShareClient) GetShare(ctx context.Context, resourceID string) (*shares.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShare", ctx, resourceID)
	ret0, _ := ret[0].(*shares.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShare indicates an expected call of GetShare.
func (mr *MockShareClientMockRecorder) GetShare(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShare", reflect.TypeOf((*MockShareClient)(nil).GetShare), ctx, resourceID)
}

// ListShares mocks base method.
func (m *MockShareClient) ListShares(ctx context.Context, listOpts shares.ListOptsBuilder) iter.Seq2[*shares.Share, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShares", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*shares.Share, error])
	return ret0
}

// ListShares indicates an expected call of ListShares.
func (mr *MockShareClientMockRecorder) ListShares(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShares", reflect.TypeOf((*MockShareClient)(nil).ListShares), ctx, listOpts)
}

// UpdateShare mocks base method.
func (m *MockShareClient) UpdateShare(ctx context.Context, id string, opts shares.UpdateOptsBuilder) (*shares.Share, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShare", ctx, id, opts)
	ret0, _ := ret[0].(*shares.Share)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateShare indicates an expected call of UpdateShare.
func (mr *MockShareClientMockRecorder) UpdateShare(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShare", reflect.TypeOf((*MockShareClient)(nil).UpdateShare), ctx, id, opts)
}
