/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../subnetpool.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=subnetpool.go -source=../subnetpool.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock SubnetPoolClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	subnetpools "github.com/gophercloud/gophercloud/v2/openstack/networking/v2/extensions/subnetpools"
	gomock "go.uber.org/mock/gomock"
)

// MockSubnetPoolClient is a mock of SubnetPoolClient interface.
type MockSubnetPoolClient struct {
	ctrl     *gomock.Controller
	recorder *MockSubnetPoolClientMockRecorder
	isgomock struct{}
}

// MockSubnetPoolClientMockRecorder is the mock recorder for MockSubnetPoolClient.
type MockSubnetPoolClientMockRecorder struct {
	mock *MockSubnetPoolClient
}

// NewMockSubnetPoolClient creates a new mock instance.
func NewMockSubnetPoolClient(ctrl *gomock.Controller) *MockSubnetPoolClient {
	mock := &MockSubnetPoolClient{ctrl: ctrl}
	mock.recorder = &MockSubnetPoolClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubnetPoolClient) EXPECT() *MockSubnetPoolClientMockRecorder {
	return m.recorder
}

// CreateSubnetPool mocks base method.
func (m *MockSubnetPoolClient) CreateSubnetPool(ctx context.Context, opts subnetpools.CreateOptsBuilder) (*subnetpools.SubnetPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSubnetPool", ctx, opts)
	ret0, _ := ret[0].(*subnetpools.SubnetPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSubnetPool indicates an expected call of CreateSubnetPool.
func (mr *MockSubnetPoolClientMockRecorder) CreateSubnetPool(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSubnetPool", reflect.TypeOf((*MockSubnetPoolClient)(nil).CreateSubnetPool), ctx, opts)
}

// DeleteSubnetPool mocks base method.
func (m *MockSubnetPoolClient) DeleteSubnetPool(ctx context.Context, resourceID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubnetPool", ctx, resourceID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubnetPool indicates an expected call of DeleteSubnetPool.
func (mr *MockSubnetPoolClientMockRecorder) DeleteSubnetPool(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubnetPool", reflect.TypeOf((*MockSubnetPoolClient)(nil).DeleteSubnetPool), ctx, resourceID)
}

// GetSubnetPool mocks base method.
func (m *MockSubnetPoolClient) GetSubnetPool(ctx context.Context, resourceID string) (*subnetpools.SubnetPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubnetPool", ctx, resourceID)
	ret0, _ := ret[0].(*subnetpools.SubnetPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubnetPool indicates an expected call of GetSubnetPool.
func (mr *MockSubnetPoolClientMockRecorder) GetSubnetPool(ctx, resourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubnetPool", reflect.TypeOf((*MockSubnetPoolClient)(nil).GetSubnetPool), ctx, resourceID)
}

// ListSubnetPools mocks base method.
func (m *MockSubnetPoolClient) ListSubnetPools(ctx context.Context, listOpts subnetpools.ListOptsBuilder) iter.Seq2[*subnetpools.SubnetPool, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubnetPools", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*subnetpools.SubnetPool, error])
	return ret0
}

// ListSubnetPools indicates an expected call of ListSubnetPools.
func (mr *MockSubnetPoolClientMockRecorder) ListSubnetPools(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubnetPools", reflect.TypeOf((*MockSubnetPoolClient)(nil).ListSubnetPools), ctx, listOpts)
}

// UpdateSubnetPool mocks base method.
func (m *MockSubnetPoolClient) UpdateSubnetPool(ctx context.Context, id string, opts subnetpools.UpdateOptsBuilder) (*subnetpools.SubnetPool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSubnetPool", ctx, id, opts)
	ret0, _ := ret[0].(*subnetpools.SubnetPool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSubnetPool indicates an expected call of UpdateSubnetPool.
func (mr *MockSubnetPoolClientMockRecorder) UpdateSubnetPool(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSubnetPool", reflect.TypeOf((*MockSubnetPoolClient)(nil).UpdateSubnetPool), ctx, id, opts)
}
