/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by MockGen. DO NOT EDIT.
// Source: ../swiftcontainer.go
//
// Generated by this command:
//
//	mockgen -package mock -destination=swiftcontainer.go -source=../swiftcontainer.go github.com/k-orc/openstack-resource-controller/internal/osclients/mock SwiftContainerClient
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	iter "iter"
	reflect "reflect"

	containers "github.com/gophercloud/gophercloud/v2/openstack/objectstorage/v1/containers"
	gomock "go.uber.org/mock/gomock"
)

// MockSwiftContainerClient is a mock of SwiftContainerClient interface.
type MockSwiftContainerClient struct {
	ctrl     *gomock.Controller
	recorder *MockSwiftContainerClientMockRecorder
	isgomock struct{}
}

// MockSwiftContainerClientMockRecorder is the mock recorder for MockSwiftContainerClient.
type MockSwiftContainerClientMockRecorder struct {
	mock *MockSwiftContainerClient
}

// NewMockSwiftContainerClient creates a new mock instance.
func NewMockSwiftContainerClient(ctrl *gomock.Controller) *MockSwiftContainerClient {
	mock := &MockSwiftContainerClient{ctrl: ctrl}
	mock.recorder = &MockSwiftContainerClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSwiftContainerClient) EXPECT() *MockSwiftContainerClientMockRecorder {
	return m.recorder
}

// CreateContainer mocks base method.
func (m *MockSwiftContainerClient) CreateContainer(ctx context.Context, containerName string, opts containers.CreateOptsBuilder) (*containers.CreateHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateContainer", ctx, containerName, opts)
	ret0, _ := ret[0].(*containers.CreateHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateContainer indicates an expected call of CreateContainer.
func (mr *MockSwiftContainerClientMockRecorder) CreateContainer(ctx, containerName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateContainer", reflect.TypeOf((*MockSwiftContainerClient)(nil).CreateContainer), ctx, containerName, opts)
}

// DeleteContainer mocks base method.
func (m *MockSwiftContainerClient) DeleteContainer(ctx context.Context, containerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteContainer", ctx, containerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteContainer indicates an expected call of DeleteContainer.
func (mr *MockSwiftContainerClientMockRecorder) DeleteContainer(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteContainer", reflect.TypeOf((*MockSwiftContainerClient)(nil).DeleteContainer), ctx, containerName)
}

// GetContainer mocks base method.
func (m *MockSwiftContainerClient) GetContainer(ctx context.Context, containerName string, opts containers.GetOptsBuilder) (*containers.GetHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainer", ctx, containerName, opts)
	ret0, _ := ret[0].(*containers.GetHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainer indicates an expected call of GetContainer.
func (mr *MockSwiftContainerClientMockRecorder) GetContainer(ctx, containerName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainer", reflect.TypeOf((*MockSwiftContainerClient)(nil).GetContainer), ctx, containerName, opts)
}

// GetContainerMetadata mocks base method.
func (m *MockSwiftContainerClient) GetContainerMetadata(ctx context.Context, containerName string) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContainerMetadata", ctx, containerName)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContainerMetadata indicates an expected call of GetContainerMetadata.
func (mr *MockSwiftContainerClientMockRecorder) GetContainerMetadata(ctx, containerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContainerMetadata", reflect.TypeOf((*MockSwiftContainerClient)(nil).GetContainerMetadata), ctx, containerName)
}

// ListContainers mocks base method.
func (m *MockSwiftContainerClient) ListContainers(ctx context.Context, listOpts containers.ListOptsBuilder) iter.Seq2[*containers.Container, error] {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListContainers", ctx, listOpts)
	ret0, _ := ret[0].(iter.Seq2[*containers.Container, error])
	return ret0
}

// ListContainers indicates an expected call of ListContainers.
func (mr *MockSwiftContainerClientMockRecorder) ListContainers(ctx, listOpts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListContainers", reflect.TypeOf((*MockSwiftContainerClient)(nil).ListContainers), ctx, listOpts)
}

// UpdateContainer mocks base method.
func (m *MockSwiftContainerClient) UpdateContainer(ctx context.Context, containerName string, opts containers.UpdateOptsBuilder) (*containers.UpdateHeader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateContainer", ctx, containerName, opts)
	ret0, _ := ret[0].(*containers.UpdateHeader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateContainer indicates an expected call of UpdateContainer.
func (mr *MockSwiftContainerClientMockRecorder) UpdateContainer(ctx, containerName, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateContainer", reflect.TypeOf((*MockSwiftContainerClient)(nil).UpdateContainer), ctx, containerName, opts)
}
