/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// DNSZoneResourceSpecApplyConfiguration represents a declarative configuration of the DNSZoneResourceSpec type for use
// with apply.
type DNSZoneResourceSpecApplyConfiguration struct {
	Name        *apiv1alpha1.OpenStackName `json:"name,omitempty"`
	Email       *string                    `json:"email,omitempty"`
	Description *string                    `json:"description,omitempty"`
	TTL         *int32                     `json:"ttl,omitempty"`
	Type        *apiv1alpha1.DNSZoneType   `json:"type,omitempty"`
	Masters     []string                   `json:"masters,omitempty"`
}

// DNSZoneResourceSpecApplyConfiguration constructs a declarative configuration of the DNSZoneResourceSpec type for use with
// apply.
func DNSZoneResourceSpec() *DNSZoneResourceSpecApplyConfiguration {
	return &DNSZoneResourceSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *DNSZoneResourceSpecApplyConfiguration) WithName(value apiv1alpha1.OpenStackName) *DNSZoneResourceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithEmail sets the Email field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Email field is set to the value of the last call.
func (b *DNSZoneResourceSpecApplyConfiguration) WithEmail(value string) *DNSZoneResourceSpecApplyConfiguration {
	b.Email = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *DNSZoneResourceSpecApplyConfiguration) WithDescription(value string) *DNSZoneResourceSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithTTL sets the TTL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTL field is set to the value of the last call.
func (b *DNSZoneResourceSpecApplyConfiguration) WithTTL(value int32) *DNSZoneResourceSpecApplyConfiguration {
	b.TTL = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *DNSZoneResourceSpecApplyConfiguration) WithType(value apiv1alpha1.DNSZoneType) *DNSZoneResourceSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithMasters adds the given value to the Masters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Masters field.
func (b *DNSZoneResourceSpecApplyConfiguration) WithMasters(values ...string) *DNSZoneResourceSpecApplyConfiguration {
	for i := range values {
		b.Masters = append(b.Masters, values[i])
	}
	return b
}
