/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// LBPoolMemberSpecApplyConfiguration represents a declarative configuration of the LBPoolMemberSpec type for use
// with apply.
type LBPoolMemberSpecApplyConfiguration struct {
	Name         *string                        `json:"name,omitempty"`
	Address      *apiv1alpha1.IPvAny            `json:"address,omitempty"`
	ProtocolPort *int32                         `json:"protocolPort,omitempty"`
	SubnetRef    *apiv1alpha1.KubernetesNameRef `json:"subnetRef,omitempty"`
	Weight       *int32                         `json:"weight,omitempty"`
	Backup       *bool                          `json:"backup,omitempty"`
	AdminStateUp *bool                          `json:"adminStateUp,omitempty"`
}

// LBPoolMemberSpecApplyConfiguration constructs a declarative configuration of the LBPoolMemberSpec type for use with
// apply.
func LBPoolMemberSpec() *LBPoolMemberSpecApplyConfiguration {
	return &LBPoolMemberSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LBPoolMemberSpecApplyConfiguration) WithName(value string) *LBPoolMemberSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithAddress sets the Address field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Address field is set to the value of the last call.
func (b *LBPoolMemberSpecApplyConfiguration) WithAddress(value apiv1alpha1.IPvAny) *LBPoolMemberSpecApplyConfiguration {
	b.Address = &value
	return b
}

// WithProtocolPort sets the ProtocolPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolPort field is set to the value of the last call.
func (b *LBPoolMemberSpecApplyConfiguration) WithProtocolPort(value int32) *LBPoolMemberSpecApplyConfiguration {
	b.ProtocolPort = &value
	return b
}

// WithSubnetRef sets the SubnetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SubnetRef field is set to the value of the last call.
func (b *LBPoolMemberSpecApplyConfiguration) WithSubnetRef(value apiv1alpha1.KubernetesNameRef) *LBPoolMemberSpecApplyConfiguration {
	b.SubnetRef = &value
	return b
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *LBPoolMemberSpecApplyConfiguration) WithWeight(value int32) *LBPoolMemberSpecApplyConfiguration {
	b.Weight = &value
	return b
}

// WithBackup sets the Backup field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Backup field is set to the value of the last call.
func (b *LBPoolMemberSpecApplyConfiguration) WithBackup(value bool) *LBPoolMemberSpecApplyConfiguration {
	b.Backup = &value
	return b
}

// WithAdminStateUp sets the AdminStateUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminStateUp field is set to the value of the last call.
func (b *LBPoolMemberSpecApplyConfiguration) WithAdminStateUp(value bool) *LBPoolMemberSpecApplyConfiguration {
	b.AdminStateUp = &value
	return b
}
