/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LBPoolResourceStatusApplyConfiguration represents a declarative configuration of the LBPoolResourceStatus type for use
// with apply.
type LBPoolResourceStatusApplyConfiguration struct {
	Name               *string                                     `json:"name,omitempty"`
	Description        *string                                     `json:"description,omitempty"`
	LBAlgorithm        *string                                     `json:"lbAlgorithm,omitempty"`
	Protocol           *string                                     `json:"protocol,omitempty"`
	LoadBalancerIDs    []string                                    `json:"loadBalancerIDs,omitempty"`
	ListenerIDs        []string                                    `json:"listenerIDs,omitempty"`
	ProjectID          *string                                     `json:"projectID,omitempty"`
	AdminStateUp       *bool                                       `json:"adminStateUp,omitempty"`
	ProvisioningStatus *string                                     `json:"provisioningStatus,omitempty"`
	OperatingStatus    *string                                     `json:"operatingStatus,omitempty"`
	HealthMonitorID    *string                                     `json:"healthMonitorID,omitempty"`
	Members            []LBPoolMemberStatusApplyConfiguration      `json:"members,omitempty"`
	SessionPersistence *LBPoolSessionPersistenceApplyConfiguration `json:"sessionPersistence,omitempty"`
	TLSEnabled         *bool                                       `json:"tlsEnabled,omitempty"`
	TLSContainerRef    *string                                     `json:"tlsContainerRef,omitempty"`
	CATLSContainerRef  *string                                     `json:"caTLSContainerRef,omitempty"`
	CRLContainerRef    *string                                     `json:"crlContainerRef,omitempty"`
	TLSCiphers         *string                                     `json:"tlsCiphers,omitempty"`
	TLSVersions        []string                                    `json:"tlsVersions,omitempty"`
	ALPNProtocols      []string                                    `json:"alpnProtocols,omitempty"`
	Tags               []string                                    `json:"tags,omitempty"`
}

// LBPoolResourceStatusApplyConfiguration constructs a declarative configuration of the LBPoolResourceStatus type for use with
// apply.
func LBPoolResourceStatus() *LBPoolResourceStatusApplyConfiguration {
	return &LBPoolResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithName(value string) *LBPoolResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithDescription(value string) *LBPoolResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithLBAlgorithm sets the LBAlgorithm field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LBAlgorithm field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithLBAlgorithm(value string) *LBPoolResourceStatusApplyConfiguration {
	b.LBAlgorithm = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithProtocol(value string) *LBPoolResourceStatusApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithLoadBalancerIDs adds the given value to the LoadBalancerIDs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the LoadBalancerIDs field.
func (b *LBPoolResourceStatusApplyConfiguration) WithLoadBalancerIDs(values ...string) *LBPoolResourceStatusApplyConfiguration {
	for i := range values {
		b.LoadBalancerIDs = append(b.LoadBalancerIDs, values[i])
	}
	return b
}

// WithListenerIDs adds the given value to the ListenerIDs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ListenerIDs field.
func (b *LBPoolResourceStatusApplyConfiguration) WithListenerIDs(values ...string) *LBPoolResourceStatusApplyConfiguration {
	for i := range values {
		b.ListenerIDs = append(b.ListenerIDs, values[i])
	}
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithProjectID(value string) *LBPoolResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithAdminStateUp sets the AdminStateUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminStateUp field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithAdminStateUp(value bool) *LBPoolResourceStatusApplyConfiguration {
	b.AdminStateUp = &value
	return b
}

// WithProvisioningStatus sets the ProvisioningStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningStatus field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithProvisioningStatus(value string) *LBPoolResourceStatusApplyConfiguration {
	b.ProvisioningStatus = &value
	return b
}

// WithOperatingStatus sets the OperatingStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatingStatus field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithOperatingStatus(value string) *LBPoolResourceStatusApplyConfiguration {
	b.OperatingStatus = &value
	return b
}

// WithHealthMonitorID sets the HealthMonitorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the HealthMonitorID field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithHealthMonitorID(value string) *LBPoolResourceStatusApplyConfiguration {
	b.HealthMonitorID = &value
	return b
}

// WithMembers adds the given value to the Members field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Members field.
func (b *LBPoolResourceStatusApplyConfiguration) WithMembers(values ...*LBPoolMemberStatusApplyConfiguration) *LBPoolResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMembers")
		}
		b.Members = append(b.Members, *values[i])
	}
	return b
}

// WithSessionPersistence sets the SessionPersistence field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SessionPersistence field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithSessionPersistence(value *LBPoolSessionPersistenceApplyConfiguration) *LBPoolResourceStatusApplyConfiguration {
	b.SessionPersistence = value
	return b
}

// WithTLSEnabled sets the TLSEnabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSEnabled field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithTLSEnabled(value bool) *LBPoolResourceStatusApplyConfiguration {
	b.TLSEnabled = &value
	return b
}

// WithTLSContainerRef sets the TLSContainerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSContainerRef field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithTLSContainerRef(value string) *LBPoolResourceStatusApplyConfiguration {
	b.TLSContainerRef = &value
	return b
}

// WithCATLSContainerRef sets the CATLSContainerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CATLSContainerRef field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithCATLSContainerRef(value string) *LBPoolResourceStatusApplyConfiguration {
	b.CATLSContainerRef = &value
	return b
}

// WithCRLContainerRef sets the CRLContainerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CRLContainerRef field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithCRLContainerRef(value string) *LBPoolResourceStatusApplyConfiguration {
	b.CRLContainerRef = &value
	return b
}

// WithTLSCiphers sets the TLSCiphers field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TLSCiphers field is set to the value of the last call.
func (b *LBPoolResourceStatusApplyConfiguration) WithTLSCiphers(value string) *LBPoolResourceStatusApplyConfiguration {
	b.TLSCiphers = &value
	return b
}

// WithTLSVersions adds the given value to the TLSVersions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TLSVersions field.
func (b *LBPoolResourceStatusApplyConfiguration) WithTLSVersions(values ...string) *LBPoolResourceStatusApplyConfiguration {
	for i := range values {
		b.TLSVersions = append(b.TLSVersions, values[i])
	}
	return b
}

// WithALPNProtocols adds the given value to the ALPNProtocols field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ALPNProtocols field.
func (b *LBPoolResourceStatusApplyConfiguration) WithALPNProtocols(values ...string) *LBPoolResourceStatusApplyConfiguration {
	for i := range values {
		b.ALPNProtocols = append(b.ALPNProtocols, values[i])
	}
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *LBPoolResourceStatusApplyConfiguration) WithTags(values ...string) *LBPoolResourceStatusApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}
