/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// LimitFilterApplyConfiguration represents a declarative configuration of the LimitFilter type for use
// with apply.
type LimitFilterApplyConfiguration struct {
	ServiceRef   *apiv1alpha1.KubernetesNameRef `json:"serviceRef,omitempty"`
	ProjectRef   *apiv1alpha1.KubernetesNameRef `json:"projectRef,omitempty"`
	DomainRef    *apiv1alpha1.KubernetesNameRef `json:"domainRef,omitempty"`
	ResourceName *string                        `json:"resourceName,omitempty"`
}

// LimitFilterApplyConfiguration constructs a declarative configuration of the LimitFilter type for use with
// apply.
func LimitFilter() *LimitFilterApplyConfiguration {
	return &LimitFilterApplyConfiguration{}
}

// WithServiceRef sets the ServiceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceRef field is set to the value of the last call.
func (b *LimitFilterApplyConfiguration) WithServiceRef(value apiv1alpha1.KubernetesNameRef) *LimitFilterApplyConfiguration {
	b.ServiceRef = &value
	return b
}

// WithProjectRef sets the ProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectRef field is set to the value of the last call.
func (b *LimitFilterApplyConfiguration) WithProjectRef(value apiv1alpha1.KubernetesNameRef) *LimitFilterApplyConfiguration {
	b.ProjectRef = &value
	return b
}

// WithDomainRef sets the DomainRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainRef field is set to the value of the last call.
func (b *LimitFilterApplyConfiguration) WithDomainRef(value apiv1alpha1.KubernetesNameRef) *LimitFilterApplyConfiguration {
	b.DomainRef = &value
	return b
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *LimitFilterApplyConfiguration) WithResourceName(value string) *LimitFilterApplyConfiguration {
	b.ResourceName = &value
	return b
}
