/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LimitResourceStatusApplyConfiguration represents a declarative configuration of the LimitResourceStatus type for use
// with apply.
type LimitResourceStatusApplyConfiguration struct {
	Description   *string `json:"description,omitempty"`
	ServiceID     *string `json:"serviceID,omitempty"`
	ProjectID     *string `json:"projectID,omitempty"`
	DomainID      *string `json:"domainID,omitempty"`
	ResourceLimit *int32  `json:"resourceLimit,omitempty"`
	ResourceName  *string `json:"resourceName,omitempty"`
}

// LimitResourceStatusApplyConfiguration constructs a declarative configuration of the LimitResourceStatus type for use with
// apply.
func LimitResourceStatus() *LimitResourceStatusApplyConfiguration {
	return &LimitResourceStatusApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *LimitResourceStatusApplyConfiguration) WithDescription(value string) *LimitResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithServiceID sets the ServiceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceID field is set to the value of the last call.
func (b *LimitResourceStatusApplyConfiguration) WithServiceID(value string) *LimitResourceStatusApplyConfiguration {
	b.ServiceID = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *LimitResourceStatusApplyConfiguration) WithProjectID(value string) *LimitResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithDomainID sets the DomainID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DomainID field is set to the value of the last call.
func (b *LimitResourceStatusApplyConfiguration) WithDomainID(value string) *LimitResourceStatusApplyConfiguration {
	b.DomainID = &value
	return b
}

// WithResourceLimit sets the ResourceLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceLimit field is set to the value of the last call.
func (b *LimitResourceStatusApplyConfiguration) WithResourceLimit(value int32) *LimitResourceStatusApplyConfiguration {
	b.ResourceLimit = &value
	return b
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *LimitResourceStatusApplyConfiguration) WithResourceName(value string) *LimitResourceStatusApplyConfiguration {
	b.ResourceName = &value
	return b
}
