/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ListenerResourceStatusApplyConfiguration represents a declarative configuration of the ListenerResourceStatus type for use
// with apply.
type ListenerResourceStatusApplyConfiguration struct {
	Name                 *string           `json:"name,omitempty"`
	Description          *string           `json:"description,omitempty"`
	LoadBalancerID       *string           `json:"loadBalancerID,omitempty"`
	Protocol             *string           `json:"protocol,omitempty"`
	ProtocolPort         *int32            `json:"protocolPort,omitempty"`
	AdminStateUp         *bool             `json:"adminStateUp,omitempty"`
	ConnectionLimit      *int32            `json:"connectionLimit,omitempty"`
	DefaultPoolID        *string           `json:"defaultPoolID,omitempty"`
	ProvisioningStatus   *string           `json:"provisioningStatus,omitempty"`
	OperatingStatus      *string           `json:"operatingStatus,omitempty"`
	AllowedCIDRs         []string          `json:"allowedCIDRs,omitempty"`
	TimeoutClientData    *int32            `json:"timeoutClientData,omitempty"`
	TimeoutMemberConnect *int32            `json:"timeoutMemberConnect,omitempty"`
	TimeoutMemberData    *int32            `json:"timeoutMemberData,omitempty"`
	TimeoutTCPInspect    *int32            `json:"timeoutTCPInspect,omitempty"`
	InsertHeaders        map[string]string `json:"insertHeaders,omitempty"`
	Tags                 []string          `json:"tags,omitempty"`
}

// ListenerResourceStatusApplyConfiguration constructs a declarative configuration of the ListenerResourceStatus type for use with
// apply.
func ListenerResourceStatus() *ListenerResourceStatusApplyConfiguration {
	return &ListenerResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithName(value string) *ListenerResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithDescription(value string) *ListenerResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithLoadBalancerID sets the LoadBalancerID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancerID field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithLoadBalancerID(value string) *ListenerResourceStatusApplyConfiguration {
	b.LoadBalancerID = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithProtocol(value string) *ListenerResourceStatusApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithProtocolPort sets the ProtocolPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolPort field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithProtocolPort(value int32) *ListenerResourceStatusApplyConfiguration {
	b.ProtocolPort = &value
	return b
}

// WithAdminStateUp sets the AdminStateUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminStateUp field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithAdminStateUp(value bool) *ListenerResourceStatusApplyConfiguration {
	b.AdminStateUp = &value
	return b
}

// WithConnectionLimit sets the ConnectionLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConnectionLimit field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithConnectionLimit(value int32) *ListenerResourceStatusApplyConfiguration {
	b.ConnectionLimit = &value
	return b
}

// WithDefaultPoolID sets the DefaultPoolID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultPoolID field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithDefaultPoolID(value string) *ListenerResourceStatusApplyConfiguration {
	b.DefaultPoolID = &value
	return b
}

// WithProvisioningStatus sets the ProvisioningStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningStatus field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithProvisioningStatus(value string) *ListenerResourceStatusApplyConfiguration {
	b.ProvisioningStatus = &value
	return b
}

// WithOperatingStatus sets the OperatingStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatingStatus field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithOperatingStatus(value string) *ListenerResourceStatusApplyConfiguration {
	b.OperatingStatus = &value
	return b
}

// WithAllowedCIDRs adds the given value to the AllowedCIDRs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedCIDRs field.
func (b *ListenerResourceStatusApplyConfiguration) WithAllowedCIDRs(values ...string) *ListenerResourceStatusApplyConfiguration {
	for i := range values {
		b.AllowedCIDRs = append(b.AllowedCIDRs, values[i])
	}
	return b
}

// WithTimeoutClientData sets the TimeoutClientData field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutClientData field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithTimeoutClientData(value int32) *ListenerResourceStatusApplyConfiguration {
	b.TimeoutClientData = &value
	return b
}

// WithTimeoutMemberConnect sets the TimeoutMemberConnect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutMemberConnect field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithTimeoutMemberConnect(value int32) *ListenerResourceStatusApplyConfiguration {
	b.TimeoutMemberConnect = &value
	return b
}

// WithTimeoutMemberData sets the TimeoutMemberData field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutMemberData field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithTimeoutMemberData(value int32) *ListenerResourceStatusApplyConfiguration {
	b.TimeoutMemberData = &value
	return b
}

// WithTimeoutTCPInspect sets the TimeoutTCPInspect field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TimeoutTCPInspect field is set to the value of the last call.
func (b *ListenerResourceStatusApplyConfiguration) WithTimeoutTCPInspect(value int32) *ListenerResourceStatusApplyConfiguration {
	b.TimeoutTCPInspect = &value
	return b
}

// WithInsertHeaders puts the entries into the InsertHeaders field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the InsertHeaders field,
// overwriting an existing map entries in InsertHeaders field with the same key.
func (b *ListenerResourceStatusApplyConfiguration) WithInsertHeaders(entries map[string]string) *ListenerResourceStatusApplyConfiguration {
	if b.InsertHeaders == nil && len(entries) > 0 {
		b.InsertHeaders = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.InsertHeaders[k] = v
	}
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *ListenerResourceStatusApplyConfiguration) WithTags(values ...string) *ListenerResourceStatusApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}
