/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// ListenerFilterApplyConfiguration represents a declarative configuration of the ListenerFilter type for use
// with apply.
type ListenerFilterApplyConfiguration struct {
	Name            *apiv1alpha1.OpenStackName     `json:"name,omitempty"`
	Description     *string                        `json:"description,omitempty"`
	LoadBalancerRef *apiv1alpha1.KubernetesNameRef `json:"loadBalancerRef,omitempty"`
	Protocol        *apiv1alpha1.ListenerProtocol  `json:"protocol,omitempty"`
	ProtocolPort    *int32                         `json:"protocolPort,omitempty"`
	Tags            []apiv1alpha1.ListenerTag      `json:"tags,omitempty"`
	TagsAny         []apiv1alpha1.ListenerTag      `json:"tagsAny,omitempty"`
	NotTags         []apiv1alpha1.ListenerTag      `json:"notTags,omitempty"`
	NotTagsAny      []apiv1alpha1.ListenerTag      `json:"notTagsAny,omitempty"`
}

// ListenerFilterApplyConfiguration constructs a declarative configuration of the ListenerFilter type for use with
// apply.
func ListenerFilter() *ListenerFilterApplyConfiguration {
	return &ListenerFilterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ListenerFilterApplyConfiguration) WithName(value apiv1alpha1.OpenStackName) *ListenerFilterApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *ListenerFilterApplyConfiguration) WithDescription(value string) *ListenerFilterApplyConfiguration {
	b.Description = &value
	return b
}

// WithLoadBalancerRef sets the LoadBalancerRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LoadBalancerRef field is set to the value of the last call.
func (b *ListenerFilterApplyConfiguration) WithLoadBalancerRef(value apiv1alpha1.KubernetesNameRef) *ListenerFilterApplyConfiguration {
	b.LoadBalancerRef = &value
	return b
}

// WithProtocol sets the Protocol field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Protocol field is set to the value of the last call.
func (b *ListenerFilterApplyConfiguration) WithProtocol(value apiv1alpha1.ListenerProtocol) *ListenerFilterApplyConfiguration {
	b.Protocol = &value
	return b
}

// WithProtocolPort sets the ProtocolPort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtocolPort field is set to the value of the last call.
func (b *ListenerFilterApplyConfiguration) WithProtocolPort(value int32) *ListenerFilterApplyConfiguration {
	b.ProtocolPort = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *ListenerFilterApplyConfiguration) WithTags(values ...apiv1alpha1.ListenerTag) *ListenerFilterApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}

// WithTagsAny adds the given value to the TagsAny field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TagsAny field.
func (b *ListenerFilterApplyConfiguration) WithTagsAny(values ...apiv1alpha1.ListenerTag) *ListenerFilterApplyConfiguration {
	for i := range values {
		b.TagsAny = append(b.TagsAny, values[i])
	}
	return b
}

// WithNotTags adds the given value to the NotTags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NotTags field.
func (b *ListenerFilterApplyConfiguration) WithNotTags(values ...apiv1alpha1.ListenerTag) *ListenerFilterApplyConfiguration {
	for i := range values {
		b.NotTags = append(b.NotTags, values[i])
	}
	return b
}

// WithNotTagsAny adds the given value to the NotTagsAny field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NotTagsAny field.
func (b *ListenerFilterApplyConfiguration) WithNotTagsAny(values ...apiv1alpha1.ListenerTag) *ListenerFilterApplyConfiguration {
	for i := range values {
		b.NotTagsAny = append(b.NotTagsAny, values[i])
	}
	return b
}
