/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LoadBalancerResourceStatusApplyConfiguration represents a declarative configuration of the LoadBalancerResourceStatus type for use
// with apply.
type LoadBalancerResourceStatusApplyConfiguration struct {
	Name               *string  `json:"name,omitempty"`
	Description        *string  `json:"description,omitempty"`
	VIPSubnetID        *string  `json:"vipSubnetID,omitempty"`
	VIPNetworkID       *string  `json:"vipNetworkID,omitempty"`
	VIPPortID          *string  `json:"vipPortID,omitempty"`
	FlavorID           *string  `json:"flavorID,omitempty"`
	ProjectID          *string  `json:"projectID,omitempty"`
	AdminStateUp       *bool    `json:"adminStateUp,omitempty"`
	Tags               []string `json:"tags,omitempty"`
	AvailabilityZone   *string  `json:"availabilityZone,omitempty"`
	ProvisioningStatus *string  `json:"provisioningStatus,omitempty"`
	OperatingStatus    *string  `json:"operatingStatus,omitempty"`
	Provider           *string  `json:"provider,omitempty"`
	VIPAddress         *string  `json:"vipAddress,omitempty"`
}

// LoadBalancerResourceStatusApplyConfiguration constructs a declarative configuration of the LoadBalancerResourceStatus type for use with
// apply.
func LoadBalancerResourceStatus() *LoadBalancerResourceStatusApplyConfiguration {
	return &LoadBalancerResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithName(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithDescription(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithVIPSubnetID sets the VIPSubnetID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VIPSubnetID field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithVIPSubnetID(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.VIPSubnetID = &value
	return b
}

// WithVIPNetworkID sets the VIPNetworkID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VIPNetworkID field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithVIPNetworkID(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.VIPNetworkID = &value
	return b
}

// WithVIPPortID sets the VIPPortID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VIPPortID field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithVIPPortID(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.VIPPortID = &value
	return b
}

// WithFlavorID sets the FlavorID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FlavorID field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithFlavorID(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.FlavorID = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithProjectID(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithAdminStateUp sets the AdminStateUp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AdminStateUp field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithAdminStateUp(value bool) *LoadBalancerResourceStatusApplyConfiguration {
	b.AdminStateUp = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithTags(values ...string) *LoadBalancerResourceStatusApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}

// WithAvailabilityZone sets the AvailabilityZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailabilityZone field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithAvailabilityZone(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.AvailabilityZone = &value
	return b
}

// WithProvisioningStatus sets the ProvisioningStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProvisioningStatus field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithProvisioningStatus(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.ProvisioningStatus = &value
	return b
}

// WithOperatingStatus sets the OperatingStatus field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the OperatingStatus field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithOperatingStatus(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.OperatingStatus = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithProvider(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.Provider = &value
	return b
}

// WithVIPAddress sets the VIPAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VIPAddress field is set to the value of the last call.
func (b *LoadBalancerResourceStatusApplyConfiguration) WithVIPAddress(value string) *LoadBalancerResourceStatusApplyConfiguration {
	b.VIPAddress = &value
	return b
}
