/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// LoadBalancerFilterApplyConfiguration represents a declarative configuration of the LoadBalancerFilter type for use
// with apply.
type LoadBalancerFilterApplyConfiguration struct {
	Name             *apiv1alpha1.OpenStackName     `json:"name,omitempty"`
	Description      *string                        `json:"description,omitempty"`
	ProjectRef       *apiv1alpha1.KubernetesNameRef `json:"projectRef,omitempty"`
	VipSubnetRef     *apiv1alpha1.KubernetesNameRef `json:"vipSubnetRef,omitempty"`
	VipNetworkRef    *apiv1alpha1.KubernetesNameRef `json:"vipNetworkRef,omitempty"`
	VipPortRef       *apiv1alpha1.KubernetesNameRef `json:"vipPortRef,omitempty"`
	AvailabilityZone *string                        `json:"availabilityZone,omitempty"`
	Provider         *string                        `json:"provider,omitempty"`
	VipAddress       *string                        `json:"vipAddress,omitempty"`
	Tags             []apiv1alpha1.LoadBalancerTag  `json:"tags,omitempty"`
	TagsAny          []apiv1alpha1.LoadBalancerTag  `json:"tagsAny,omitempty"`
	NotTags          []apiv1alpha1.LoadBalancerTag  `json:"notTags,omitempty"`
	NotTagsAny       []apiv1alpha1.LoadBalancerTag  `json:"notTagsAny,omitempty"`
}

// LoadBalancerFilterApplyConfiguration constructs a declarative configuration of the LoadBalancerFilter type for use with
// apply.
func LoadBalancerFilter() *LoadBalancerFilterApplyConfiguration {
	return &LoadBalancerFilterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithName(value apiv1alpha1.OpenStackName) *LoadBalancerFilterApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithDescription(value string) *LoadBalancerFilterApplyConfiguration {
	b.Description = &value
	return b
}

// WithProjectRef sets the ProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectRef field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithProjectRef(value apiv1alpha1.KubernetesNameRef) *LoadBalancerFilterApplyConfiguration {
	b.ProjectRef = &value
	return b
}

// WithVipSubnetRef sets the VipSubnetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VipSubnetRef field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithVipSubnetRef(value apiv1alpha1.KubernetesNameRef) *LoadBalancerFilterApplyConfiguration {
	b.VipSubnetRef = &value
	return b
}

// WithVipNetworkRef sets the VipNetworkRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VipNetworkRef field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithVipNetworkRef(value apiv1alpha1.KubernetesNameRef) *LoadBalancerFilterApplyConfiguration {
	b.VipNetworkRef = &value
	return b
}

// WithVipPortRef sets the VipPortRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VipPortRef field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithVipPortRef(value apiv1alpha1.KubernetesNameRef) *LoadBalancerFilterApplyConfiguration {
	b.VipPortRef = &value
	return b
}

// WithAvailabilityZone sets the AvailabilityZone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AvailabilityZone field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithAvailabilityZone(value string) *LoadBalancerFilterApplyConfiguration {
	b.AvailabilityZone = &value
	return b
}

// WithProvider sets the Provider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Provider field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithProvider(value string) *LoadBalancerFilterApplyConfiguration {
	b.Provider = &value
	return b
}

// WithVipAddress sets the VipAddress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VipAddress field is set to the value of the last call.
func (b *LoadBalancerFilterApplyConfiguration) WithVipAddress(value string) *LoadBalancerFilterApplyConfiguration {
	b.VipAddress = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *LoadBalancerFilterApplyConfiguration) WithTags(values ...apiv1alpha1.LoadBalancerTag) *LoadBalancerFilterApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}

// WithTagsAny adds the given value to the TagsAny field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the TagsAny field.
func (b *LoadBalancerFilterApplyConfiguration) WithTagsAny(values ...apiv1alpha1.LoadBalancerTag) *LoadBalancerFilterApplyConfiguration {
	for i := range values {
		b.TagsAny = append(b.TagsAny, values[i])
	}
	return b
}

// WithNotTags adds the given value to the NotTags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NotTags field.
func (b *LoadBalancerFilterApplyConfiguration) WithNotTags(values ...apiv1alpha1.LoadBalancerTag) *LoadBalancerFilterApplyConfiguration {
	for i := range values {
		b.NotTags = append(b.NotTags, values[i])
	}
	return b
}

// WithNotTagsAny adds the given value to the NotTagsAny field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the NotTagsAny field.
func (b *LoadBalancerFilterApplyConfiguration) WithNotTagsAny(values ...apiv1alpha1.LoadBalancerTag) *LoadBalancerFilterApplyConfiguration {
	for i := range values {
		b.NotTagsAny = append(b.NotTagsAny, values[i])
	}
	return b
}
