/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/k-orc/openstack-resource-controller/api/v1alpha1"
)

// PortResourceSpecApplyConfiguration represents a declarative configuration of the PortResourceSpec type for use
// with apply.
type PortResourceSpecApplyConfiguration struct {
	Name                *v1alpha1.OpenStackName                `json:"name,omitempty"`
	Description         *v1alpha1.OpenStackDescription         `json:"description,omitempty"`
	Tags                []v1alpha1.NeutronTag                  `json:"tags,omitempty"`
	ProjectID           *v1alpha1.UUID                         `json:"projectID,omitempty"`
	AllowedAddressPairs []AllowedAddressPairApplyConfiguration `json:"allowedAddressPairs,omitempty"`
	Addresses           []AddressApplyConfiguration            `json:"addresses,omitempty"`
	SecurityGroupRefs   []v1alpha1.OpenStackName               `json:"securityGroupRefs,omitempty"`
}

// PortResourceSpecApplyConfiguration constructs a declarative configuration of the PortResourceSpec type for use with
// apply.
func PortResourceSpec() *PortResourceSpecApplyConfiguration {
	return &PortResourceSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *PortResourceSpecApplyConfiguration) WithName(value v1alpha1.OpenStackName) *PortResourceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *PortResourceSpecApplyConfiguration) WithDescription(value v1alpha1.OpenStackDescription) *PortResourceSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *PortResourceSpecApplyConfiguration) WithTags(values ...v1alpha1.NeutronTag) *PortResourceSpecApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *PortResourceSpecApplyConfiguration) WithProjectID(value v1alpha1.UUID) *PortResourceSpecApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithAllowedAddressPairs adds the given value to the AllowedAddressPairs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the AllowedAddressPairs field.
func (b *PortResourceSpecApplyConfiguration) WithAllowedAddressPairs(values ...*AllowedAddressPairApplyConfiguration) *PortResourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAllowedAddressPairs")
		}
		b.AllowedAddressPairs = append(b.AllowedAddressPairs, *values[i])
	}
	return b
}

// WithAddresses adds the given value to the Addresses field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Addresses field.
func (b *PortResourceSpecApplyConfiguration) WithAddresses(values ...*AddressApplyConfiguration) *PortResourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithAddresses")
		}
		b.Addresses = append(b.Addresses, *values[i])
	}
	return b
}

// WithSecurityGroupRefs adds the given value to the SecurityGroupRefs field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the SecurityGroupRefs field.
func (b *PortResourceSpecApplyConfiguration) WithSecurityGroupRefs(values ...v1alpha1.OpenStackName) *PortResourceSpecApplyConfiguration {
	for i := range values {
		b.SecurityGroupRefs = append(b.SecurityGroupRefs, values[i])
	}
	return b
}
