/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// QosMinimumPacketRateRuleStatusApplyConfiguration represents a declarative configuration of the QosMinimumPacketRateRuleStatus type for use
// with apply.
type QosMinimumPacketRateRuleStatusApplyConfiguration struct {
	ID        *string `json:"id,omitempty"`
	Direction *string `json:"direction,omitempty"`
	Minkpps   *int32  `json:"minkpps,omitempty"`
}

// QosMinimumPacketRateRuleStatusApplyConfiguration constructs a declarative configuration of the QosMinimumPacketRateRuleStatus type for use with
// apply.
func QosMinimumPacketRateRuleStatus() *QosMinimumPacketRateRuleStatusApplyConfiguration {
	return &QosMinimumPacketRateRuleStatusApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *QosMinimumPacketRateRuleStatusApplyConfiguration) WithID(value string) *QosMinimumPacketRateRuleStatusApplyConfiguration {
	b.ID = &value
	return b
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *QosMinimumPacketRateRuleStatusApplyConfiguration) WithDirection(value string) *QosMinimumPacketRateRuleStatusApplyConfiguration {
	b.Direction = &value
	return b
}

// WithMinkpps sets the Minkpps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Minkpps field is set to the value of the last call.
func (b *QosMinimumPacketRateRuleStatusApplyConfiguration) WithMinkpps(value int32) *QosMinimumPacketRateRuleStatusApplyConfiguration {
	b.Minkpps = &value
	return b
}
