/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// QosMinimumPacketRateLimitRuleApplyConfiguration represents a declarative configuration of the QosMinimumPacketRateLimitRule type for use
// with apply.
type QosMinimumPacketRateLimitRuleApplyConfiguration struct {
	Direction    *apiv1alpha1.RuleDirection `json:"direction,omitempty"`
	Maxkpps      *int32                     `json:"maxkpps,omitempty"`
	MaxBurstkpps *int32                     `json:"maxburstkpps,omitempty"`
}

// QosMinimumPacketRateLimitRuleApplyConfiguration constructs a declarative configuration of the QosMinimumPacketRateLimitRule type for use with
// apply.
func QosMinimumPacketRateLimitRule() *QosMinimumPacketRateLimitRuleApplyConfiguration {
	return &QosMinimumPacketRateLimitRuleApplyConfiguration{}
}

// WithDirection sets the Direction field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Direction field is set to the value of the last call.
func (b *QosMinimumPacketRateLimitRuleApplyConfiguration) WithDirection(value apiv1alpha1.RuleDirection) *QosMinimumPacketRateLimitRuleApplyConfiguration {
	b.Direction = &value
	return b
}

// WithMaxkpps sets the Maxkpps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Maxkpps field is set to the value of the last call.
func (b *QosMinimumPacketRateLimitRuleApplyConfiguration) WithMaxkpps(value int32) *QosMinimumPacketRateLimitRuleApplyConfiguration {
	b.Maxkpps = &value
	return b
}

// WithMaxBurstkpps sets the MaxBurstkpps field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxBurstkpps field is set to the value of the last call.
func (b *QosMinimumPacketRateLimitRuleApplyConfiguration) WithMaxBurstkpps(value int32) *QosMinimumPacketRateLimitRuleApplyConfiguration {
	b.MaxBurstkpps = &value
	return b
}
