/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// QosPolicyResourceStatusApplyConfiguration represents a declarative configuration of the QosPolicyResourceStatus type for use
// with apply.
type QosPolicyResourceStatusApplyConfiguration struct {
	Name                                    *string                                                 `json:"name,omitempty"`
	Description                             *string                                                 `json:"description,omitempty"`
	ProjectID                               *string                                                 `json:"projectID,omitempty"`
	Tags                                    []string                                                `json:"tags,omitempty"`
	Shared                                  *bool                                                   `json:"shared,omitempty"`
	BandWidthLimitRules                     []QosBandwidthLimitRuleStatusApplyConfiguration         `json:"bandwidthlimitrules,omitempty"`
	DscpMarkingRules                        []QosDscpMarkingRuleStatusApplyConfiguration            `json:"dscpmarkingrules,omitempty"`
	MinimumBandwidthRules                   []QosMinimumBandwidthRuleStatusApplyConfiguration       `json:"minimumbandwidthrules,omitempty"`
	MinimumPacketRateRules                  []QosMinimumPacketRateRuleStatusApplyConfiguration      `json:"minimumpacketraterules,omitempty"`
	MinimumPacketRateLimitRules             []QosMinimumPacketRateLimitRuleStatusApplyConfiguration `json:"minimumpacketratelimitrules,omitempty"`
	NeutronStatusMetadataApplyConfiguration `json:",inline"`
}

// QosPolicyResourceStatusApplyConfiguration constructs a declarative configuration of the QosPolicyResourceStatus type for use with
// apply.
func QosPolicyResourceStatus() *QosPolicyResourceStatusApplyConfiguration {
	return &QosPolicyResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *QosPolicyResourceStatusApplyConfiguration) WithName(value string) *QosPolicyResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *QosPolicyResourceStatusApplyConfiguration) WithDescription(value string) *QosPolicyResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *QosPolicyResourceStatusApplyConfiguration) WithProjectID(value string) *QosPolicyResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithTags adds the given value to the Tags field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Tags field.
func (b *QosPolicyResourceStatusApplyConfiguration) WithTags(values ...string) *QosPolicyResourceStatusApplyConfiguration {
	for i := range values {
		b.Tags = append(b.Tags, values[i])
	}
	return b
}

// WithShared sets the Shared field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shared field is set to the value of the last call.
func (b *QosPolicyResourceStatusApplyConfiguration) WithShared(value bool) *QosPolicyResourceStatusApplyConfiguration {
	b.Shared = &value
	return b
}

// WithBandWidthLimitRules adds the given value to the BandWidthLimitRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the BandWidthLimitRules field.
func (b *QosPolicyResourceStatusApplyConfiguration) WithBandWidthLimitRules(values ...*QosBandwidthLimitRuleStatusApplyConfiguration) *QosPolicyResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBandWidthLimitRules")
		}
		b.BandWidthLimitRules = append(b.BandWidthLimitRules, *values[i])
	}
	return b
}

// WithDscpMarkingRules adds the given value to the DscpMarkingRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the DscpMarkingRules field.
func (b *QosPolicyResourceStatusApplyConfiguration) WithDscpMarkingRules(values ...*QosDscpMarkingRuleStatusApplyConfiguration) *QosPolicyResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithDscpMarkingRules")
		}
		b.DscpMarkingRules = append(b.DscpMarkingRules, *values[i])
	}
	return b
}

// WithMinimumBandwidthRules adds the given value to the MinimumBandwidthRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MinimumBandwidthRules field.
func (b *QosPolicyResourceStatusApplyConfiguration) WithMinimumBandwidthRules(values ...*QosMinimumBandwidthRuleStatusApplyConfiguration) *QosPolicyResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMinimumBandwidthRules")
		}
		b.MinimumBandwidthRules = append(b.MinimumBandwidthRules, *values[i])
	}
	return b
}

// WithMinimumPacketRateRules adds the given value to the MinimumPacketRateRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MinimumPacketRateRules field.
func (b *QosPolicyResourceStatusApplyConfiguration) WithMinimumPacketRateRules(values ...*QosMinimumPacketRateRuleStatusApplyConfiguration) *QosPolicyResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMinimumPacketRateRules")
		}
		b.MinimumPacketRateRules = append(b.MinimumPacketRateRules, *values[i])
	}
	return b
}

// WithMinimumPacketRateLimitRules adds the given value to the MinimumPacketRateLimitRules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the MinimumPacketRateLimitRules field.
func (b *QosPolicyResourceStatusApplyConfiguration) WithMinimumPacketRateLimitRules(values ...*QosMinimumPacketRateLimitRuleStatusApplyConfiguration) *QosPolicyResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMinimumPacketRateLimitRules")
		}
		b.MinimumPacketRateLimitRules = append(b.MinimumPacketRateLimitRules, *values[i])
	}
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *QosPolicyResourceStatusApplyConfiguration) WithCreatedAt(value v1.Time) *QosPolicyResourceStatusApplyConfiguration {
	b.NeutronStatusMetadataApplyConfiguration.CreatedAt = &value
	return b
}

// WithUpdatedAt sets the UpdatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedAt field is set to the value of the last call.
func (b *QosPolicyResourceStatusApplyConfiguration) WithUpdatedAt(value v1.Time) *QosPolicyResourceStatusApplyConfiguration {
	b.NeutronStatusMetadataApplyConfiguration.UpdatedAt = &value
	return b
}

// WithRevisionNumber sets the RevisionNumber field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RevisionNumber field is set to the value of the last call.
func (b *QosPolicyResourceStatusApplyConfiguration) WithRevisionNumber(value int64) *QosPolicyResourceStatusApplyConfiguration {
	b.NeutronStatusMetadataApplyConfiguration.RevisionNumber = &value
	return b
}
