/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v3/api/v1alpha1"
)

// RecordSetFilterApplyConfiguration represents a declarative configuration of the RecordSetFilter type for use
// with apply.
type RecordSetFilterApplyConfiguration struct {
	ZoneRef     *apiv1alpha1.KubernetesNameRef `json:"zoneRef,omitempty"`
	Name        *apiv1alpha1.OpenStackName     `json:"name,omitempty"`
	Description *string                        `json:"description,omitempty"`
	Type        *apiv1alpha1.RecordSetType     `json:"type,omitempty"`
}

// RecordSetFilterApplyConfiguration constructs a declarative configuration of the RecordSetFilter type for use with
// apply.
func RecordSetFilter() *RecordSetFilterApplyConfiguration {
	return &RecordSetFilterApplyConfiguration{}
}

// WithZoneRef sets the ZoneRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ZoneRef field is set to the value of the last call.
func (b *RecordSetFilterApplyConfiguration) WithZoneRef(value apiv1alpha1.KubernetesNameRef) *RecordSetFilterApplyConfiguration {
	b.ZoneRef = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RecordSetFilterApplyConfiguration) WithName(value apiv1alpha1.OpenStackName) *RecordSetFilterApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *RecordSetFilterApplyConfiguration) WithDescription(value string) *RecordSetFilterApplyConfiguration {
	b.Description = &value
	return b
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *RecordSetFilterApplyConfiguration) WithType(value apiv1alpha1.RecordSetType) *RecordSetFilterApplyConfiguration {
	b.Type = &value
	return b
}
