/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RecordSetImportApplyConfiguration represents a declarative configuration of the RecordSetImport type for use
// with apply.
type RecordSetImportApplyConfiguration struct {
	ID     *string                            `json:"id,omitempty"`
	Filter *RecordSetFilterApplyConfiguration `json:"filter,omitempty"`
}

// RecordSetImportApplyConfiguration constructs a declarative configuration of the RecordSetImport type for use with
// apply.
func RecordSetImport() *RecordSetImportApplyConfiguration {
	return &RecordSetImportApplyConfiguration{}
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *RecordSetImportApplyConfiguration) WithID(value string) *RecordSetImportApplyConfiguration {
	b.ID = &value
	return b
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *RecordSetImportApplyConfiguration) WithFilter(value *RecordSetFilterApplyConfiguration) *RecordSetImportApplyConfiguration {
	b.Filter = value
	return b
}
