/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// RegisteredLimitFilterApplyConfiguration represents a declarative configuration of the RegisteredLimitFilter type for use
// with apply.
type RegisteredLimitFilterApplyConfiguration struct {
	Description  *string                        `json:"description,omitempty"`
	ServiceRef   *apiv1alpha1.KubernetesNameRef `json:"serviceRef,omitempty"`
	ResourceName *string                        `json:"resourceName,omitempty"`
}

// RegisteredLimitFilterApplyConfiguration constructs a declarative configuration of the RegisteredLimitFilter type for use with
// apply.
func RegisteredLimitFilter() *RegisteredLimitFilterApplyConfiguration {
	return &RegisteredLimitFilterApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *RegisteredLimitFilterApplyConfiguration) WithDescription(value string) *RegisteredLimitFilterApplyConfiguration {
	b.Description = &value
	return b
}

// WithServiceRef sets the ServiceRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceRef field is set to the value of the last call.
func (b *RegisteredLimitFilterApplyConfiguration) WithServiceRef(value apiv1alpha1.KubernetesNameRef) *RegisteredLimitFilterApplyConfiguration {
	b.ServiceRef = &value
	return b
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *RegisteredLimitFilterApplyConfiguration) WithResourceName(value string) *RegisteredLimitFilterApplyConfiguration {
	b.ResourceName = &value
	return b
}
