/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RegisteredLimitResourceStatusApplyConfiguration represents a declarative configuration of the RegisteredLimitResourceStatus type for use
// with apply.
type RegisteredLimitResourceStatusApplyConfiguration struct {
	Description  *string `json:"description,omitempty"`
	ResourceName *string `json:"resourceName,omitempty"`
	RegionID     *string `json:"regionID,omitempty"`
	ServiceID    *string `json:"serviceID,omitempty"`
	DefaultLimit *int32  `json:"defaultLimit,omitempty"`
}

// RegisteredLimitResourceStatusApplyConfiguration constructs a declarative configuration of the RegisteredLimitResourceStatus type for use with
// apply.
func RegisteredLimitResourceStatus() *RegisteredLimitResourceStatusApplyConfiguration {
	return &RegisteredLimitResourceStatusApplyConfiguration{}
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *RegisteredLimitResourceStatusApplyConfiguration) WithDescription(value string) *RegisteredLimitResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithResourceName sets the ResourceName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceName field is set to the value of the last call.
func (b *RegisteredLimitResourceStatusApplyConfiguration) WithResourceName(value string) *RegisteredLimitResourceStatusApplyConfiguration {
	b.ResourceName = &value
	return b
}

// WithRegionID sets the RegionID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RegionID field is set to the value of the last call.
func (b *RegisteredLimitResourceStatusApplyConfiguration) WithRegionID(value string) *RegisteredLimitResourceStatusApplyConfiguration {
	b.RegionID = &value
	return b
}

// WithServiceID sets the ServiceID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceID field is set to the value of the last call.
func (b *RegisteredLimitResourceStatusApplyConfiguration) WithServiceID(value string) *RegisteredLimitResourceStatusApplyConfiguration {
	b.ServiceID = &value
	return b
}

// WithDefaultLimit sets the DefaultLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultLimit field is set to the value of the last call.
func (b *RegisteredLimitResourceStatusApplyConfiguration) WithDefaultLimit(value int32) *RegisteredLimitResourceStatusApplyConfiguration {
	b.DefaultLimit = &value
	return b
}
