/*
Copyright 2025 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ServiceResourceSpecApplyConfiguration represents a declarative configuration of the ServiceResourceSpec type for use
// with apply.
type ServiceResourceSpecApplyConfiguration struct {
	Type    *string           `json:"type,omitempty"`
	Enabled *bool             `json:"enabled,omitempty"`
	Extra   map[string]any `json:"extra,omitempty"`
}

// ServiceResourceSpecApplyConfiguration constructs a declarative configuration of the ServiceResourceSpec type for use with
// apply.
func ServiceResourceSpec() *ServiceResourceSpecApplyConfiguration {
	return &ServiceResourceSpecApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ServiceResourceSpecApplyConfiguration) WithType(value string) *ServiceResourceSpecApplyConfiguration {
	b.Type = &value
	return b
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *ServiceResourceSpecApplyConfiguration) WithEnabled(value bool) *ServiceResourceSpecApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithExtra puts the entries into the Extra field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Extra field,
// overwriting an existing map entries in Extra field with the same key.
func (b *ServiceResourceSpecApplyConfiguration) WithExtra(entries map[string]any) *ServiceResourceSpecApplyConfiguration {
	if b.Extra == nil && len(entries) > 0 {
		b.Extra = make(map[string]any, len(entries))
	}
	for k, v := range entries {
		b.Extra[k] = v
	}
	return b
}
