/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ShareExportLocationApplyConfiguration represents a declarative configuration of the ShareExportLocation type for use
// with apply.
type ShareExportLocationApplyConfiguration struct {
	Path      *string `json:"path,omitempty"`
	Preferred *bool   `json:"preferred,omitempty"`
}

// ShareExportLocationApplyConfiguration constructs a declarative configuration of the ShareExportLocation type for use with
// apply.
func ShareExportLocation() *ShareExportLocationApplyConfiguration {
	return &ShareExportLocationApplyConfiguration{}
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *ShareExportLocationApplyConfiguration) WithPath(value string) *ShareExportLocationApplyConfiguration {
	b.Path = &value
	return b
}

// WithPreferred sets the Preferred field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Preferred field is set to the value of the last call.
func (b *ShareExportLocationApplyConfiguration) WithPreferred(value bool) *ShareExportLocationApplyConfiguration {
	b.Preferred = &value
	return b
}
