/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubnetPoolResourceStatusApplyConfiguration represents a declarative configuration of the SubnetPoolResourceStatus type for use
// with apply.
type SubnetPoolResourceStatusApplyConfiguration struct {
	Name           *string `json:"name,omitempty"`
	Description    *string `json:"description,omitempty"`
	ProjectID      *string `json:"projectID,omitempty"`
	AddressScopeID *string `json:"addressScopeID,omitempty"`
}

// SubnetPoolResourceStatusApplyConfiguration constructs a declarative configuration of the SubnetPoolResourceStatus type for use with
// apply.
func SubnetPoolResourceStatus() *SubnetPoolResourceStatusApplyConfiguration {
	return &SubnetPoolResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubnetPoolResourceStatusApplyConfiguration) WithName(value string) *SubnetPoolResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *SubnetPoolResourceStatusApplyConfiguration) WithDescription(value string) *SubnetPoolResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *SubnetPoolResourceStatusApplyConfiguration) WithProjectID(value string) *SubnetPoolResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithAddressScopeID sets the AddressScopeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AddressScopeID field is set to the value of the last call.
func (b *SubnetPoolResourceStatusApplyConfiguration) WithAddressScopeID(value string) *SubnetPoolResourceStatusApplyConfiguration {
	b.AddressScopeID = &value
	return b
}
