/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// SubnetPoolResourceSpecApplyConfiguration represents a declarative configuration of the SubnetPoolResourceSpec type for use
// with apply.
type SubnetPoolResourceSpecApplyConfiguration struct {
	Name                *apiv1alpha1.OpenStackName     `json:"name,omitempty"`
	Description         *string                        `json:"description,omitempty"`
	ProjectRef          *apiv1alpha1.KubernetesNameRef `json:"projectRef,omitempty"`
	AddressScopeRef     *apiv1alpha1.KubernetesNameRef `json:"addressScopeRef,omitempty"`
	Prefixes            []apiv1alpha1.CIDR             `json:"prefixes,omitempty"`
	MinPrefixLength     *int32                         `json:"minPrefixLength,omitempty"`
	MaxPrefixLength     *int32                         `json:"maxPrefixLength,omitempty"`
	Shared              *bool                          `json:"shared,omitempty"`
	DefaultPrefixLength *int32                         `json:"defaultPrefixLength,omitempty"`
	IsDefault           *bool                          `json:"isDefault,omitempty"`
}

// SubnetPoolResourceSpecApplyConfiguration constructs a declarative configuration of the SubnetPoolResourceSpec type for use with
// apply.
func SubnetPoolResourceSpec() *SubnetPoolResourceSpecApplyConfiguration {
	return &SubnetPoolResourceSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithName(value apiv1alpha1.OpenStackName) *SubnetPoolResourceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithDescription(value string) *SubnetPoolResourceSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithProjectRef sets the ProjectRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectRef field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithProjectRef(value apiv1alpha1.KubernetesNameRef) *SubnetPoolResourceSpecApplyConfiguration {
	b.ProjectRef = &value
	return b
}

// WithAddressScopeRef sets the AddressScopeRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AddressScopeRef field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithAddressScopeRef(value apiv1alpha1.KubernetesNameRef) *SubnetPoolResourceSpecApplyConfiguration {
	b.AddressScopeRef = &value
	return b
}

// WithPrefixes adds the given value to the Prefixes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Prefixes field.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithPrefixes(values ...apiv1alpha1.CIDR) *SubnetPoolResourceSpecApplyConfiguration {
	for i := range values {
		b.Prefixes = append(b.Prefixes, values[i])
	}
	return b
}

// WithMinPrefixLength sets the MinPrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinPrefixLength field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithMinPrefixLength(value int32) *SubnetPoolResourceSpecApplyConfiguration {
	b.MinPrefixLength = &value
	return b
}

// WithMaxPrefixLength sets the MaxPrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxPrefixLength field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithMaxPrefixLength(value int32) *SubnetPoolResourceSpecApplyConfiguration {
	b.MaxPrefixLength = &value
	return b
}

// WithShared sets the Shared field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Shared field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithShared(value bool) *SubnetPoolResourceSpecApplyConfiguration {
	b.Shared = &value
	return b
}

// WithDefaultPrefixLength sets the DefaultPrefixLength field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultPrefixLength field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithDefaultPrefixLength(value int32) *SubnetPoolResourceSpecApplyConfiguration {
	b.DefaultPrefixLength = &value
	return b
}

// WithIsDefault sets the IsDefault field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IsDefault field is set to the value of the last call.
func (b *SubnetPoolResourceSpecApplyConfiguration) WithIsDefault(value bool) *SubnetPoolResourceSpecApplyConfiguration {
	b.IsDefault = &value
	return b
}
