/*
Copyright 2025 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// SubportStatusApplyConfiguration represents a declarative configuration of the SubportStatus type for use
// with apply.
type SubportStatusApplyConfiguration struct {
	PortID           *string `json:"portID,omitempty"`
	SegmentationType *string `json:"segmentationType,omitempty"`
	SegmentationID   *int32  `json:"segmentationID,omitempty"`
}

// SubportStatusApplyConfiguration constructs a declarative configuration of the SubportStatus type for use with
// apply.
func SubportStatus() *SubportStatusApplyConfiguration {
	return &SubportStatusApplyConfiguration{}
}

// WithPortID sets the PortID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PortID field is set to the value of the last call.
func (b *SubportStatusApplyConfiguration) WithPortID(value string) *SubportStatusApplyConfiguration {
	b.PortID = &value
	return b
}

// WithSegmentationType sets the SegmentationType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SegmentationType field is set to the value of the last call.
func (b *SubportStatusApplyConfiguration) WithSegmentationType(value string) *SubportStatusApplyConfiguration {
	b.SegmentationType = &value
	return b
}

// WithSegmentationID sets the SegmentationID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SegmentationID field is set to the value of the last call.
func (b *SubportStatusApplyConfiguration) WithSegmentationID(value int32) *SubportStatusApplyConfiguration {
	b.SegmentationID = &value
	return b
}
