/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// VolumeSnapshotResourceStatusApplyConfiguration represents a declarative configuration of the VolumeSnapshotResourceStatus type for use
// with apply.
type VolumeSnapshotResourceStatusApplyConfiguration struct {
	Name            *string                                          `json:"name,omitempty"`
	Description     *string                                          `json:"description,omitempty"`
	Status          *string                                          `json:"status,omitempty"`
	Size            *int32                                           `json:"size,omitempty"`
	VolumeID        *string                                          `json:"volumeID,omitempty"`
	Metadata        []VolumeSnapshotMetadataStatusApplyConfiguration `json:"metadata,omitempty"`
	Progress        *string                                          `json:"progress,omitempty"`
	ProjectID       *string                                          `json:"projectID,omitempty"`
	UserID          *string                                          `json:"userID,omitempty"`
	GroupSnapshotID *string                                          `json:"groupSnapshotID,omitempty"`
	ConsumesQuota   *bool                                            `json:"consumesQuota,omitempty"`
	CreatedAt       *v1.Time                                         `json:"createdAt,omitempty"`
	UpdatedAt       *v1.Time                                         `json:"updatedAt,omitempty"`
}

// VolumeSnapshotResourceStatusApplyConfiguration constructs a declarative configuration of the VolumeSnapshotResourceStatus type for use with
// apply.
func VolumeSnapshotResourceStatus() *VolumeSnapshotResourceStatusApplyConfiguration {
	return &VolumeSnapshotResourceStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithName(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithDescription(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.Description = &value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithStatus(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.Status = &value
	return b
}

// WithSize sets the Size field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Size field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithSize(value int32) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.Size = &value
	return b
}

// WithVolumeID sets the VolumeID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeID field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithVolumeID(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.VolumeID = &value
	return b
}

// WithMetadata adds the given value to the Metadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Metadata field.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithMetadata(values ...*VolumeSnapshotMetadataStatusApplyConfiguration) *VolumeSnapshotResourceStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMetadata")
		}
		b.Metadata = append(b.Metadata, *values[i])
	}
	return b
}

// WithProgress sets the Progress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Progress field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithProgress(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.Progress = &value
	return b
}

// WithProjectID sets the ProjectID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProjectID field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithProjectID(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.ProjectID = &value
	return b
}

// WithUserID sets the UserID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserID field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithUserID(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.UserID = &value
	return b
}

// WithGroupSnapshotID sets the GroupSnapshotID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupSnapshotID field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithGroupSnapshotID(value string) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.GroupSnapshotID = &value
	return b
}

// WithConsumesQuota sets the ConsumesQuota field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConsumesQuota field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithConsumesQuota(value bool) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.ConsumesQuota = &value
	return b
}

// WithCreatedAt sets the CreatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreatedAt field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithCreatedAt(value v1.Time) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.CreatedAt = &value
	return b
}

// WithUpdatedAt sets the UpdatedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedAt field is set to the value of the last call.
func (b *VolumeSnapshotResourceStatusApplyConfiguration) WithUpdatedAt(value v1.Time) *VolumeSnapshotResourceStatusApplyConfiguration {
	b.UpdatedAt = &value
	return b
}
