/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// VolumeSnapshotResourceSpecApplyConfiguration represents a declarative configuration of the VolumeSnapshotResourceSpec type for use
// with apply.
type VolumeSnapshotResourceSpecApplyConfiguration struct {
	Name        *apiv1alpha1.OpenStackName                 `json:"name,omitempty"`
	Description *string                                    `json:"description,omitempty"`
	VolumeRef   *apiv1alpha1.KubernetesNameRef             `json:"volumeRef,omitempty"`
	Force       *bool                                      `json:"force,omitempty"`
	Metadata    []VolumeSnapshotMetadataApplyConfiguration `json:"metadata,omitempty"`
}

// VolumeSnapshotResourceSpecApplyConfiguration constructs a declarative configuration of the VolumeSnapshotResourceSpec type for use with
// apply.
func VolumeSnapshotResourceSpec() *VolumeSnapshotResourceSpecApplyConfiguration {
	return &VolumeSnapshotResourceSpecApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *VolumeSnapshotResourceSpecApplyConfiguration) WithName(value apiv1alpha1.OpenStackName) *VolumeSnapshotResourceSpecApplyConfiguration {
	b.Name = &value
	return b
}

// WithDescription sets the Description field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Description field is set to the value of the last call.
func (b *VolumeSnapshotResourceSpecApplyConfiguration) WithDescription(value string) *VolumeSnapshotResourceSpecApplyConfiguration {
	b.Description = &value
	return b
}

// WithVolumeRef sets the VolumeRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the VolumeRef field is set to the value of the last call.
func (b *VolumeSnapshotResourceSpecApplyConfiguration) WithVolumeRef(value apiv1alpha1.KubernetesNameRef) *VolumeSnapshotResourceSpecApplyConfiguration {
	b.VolumeRef = &value
	return b
}

// WithForce sets the Force field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Force field is set to the value of the last call.
func (b *VolumeSnapshotResourceSpecApplyConfiguration) WithForce(value bool) *VolumeSnapshotResourceSpecApplyConfiguration {
	b.Force = &value
	return b
}

// WithMetadata adds the given value to the Metadata field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Metadata field.
func (b *VolumeSnapshotResourceSpecApplyConfiguration) WithMetadata(values ...*VolumeSnapshotMetadataApplyConfiguration) *VolumeSnapshotResourceSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithMetadata")
		}
		b.Metadata = append(b.Metadata, *values[i])
	}
	return b
}
