/*
Copyright 2025 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
)

// VolumeExtraApplyConfiguration represents a declarative configuration of the VolumeExtra type for use
// with apply.
type VolumeExtraApplyConfiguration struct {
	Attachments []apiv1alpha1.KubernetesNameRef `json:"attachments,omitempty"`
}

// VolumeExtraApplyConfiguration constructs a declarative configuration of the VolumeExtra type for use with
// apply.
func VolumeExtra() *VolumeExtraApplyConfiguration {
	return &VolumeExtraApplyConfiguration{}
}

// WithAttachments adds the given value to the Attachments field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Attachments field.
func (b *VolumeExtraApplyConfiguration) WithAttachments(values ...apiv1alpha1.KubernetesNameRef) *VolumeExtraApplyConfiguration {
	for i := range values {
		b.Attachments = append(b.Attachments, values[i])
	}
	return b
}
