apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Network
metadata:
  name: orc-managed-network
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  resource:
    description: |
      Blah blah blah
    tags:
    - foo
    - bar
