/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Package kustomizeref provides a linter that ensures every KubernetesNameRef
// field in api/v1alpha1 carries an +orc:kustomize:ref=<Kind> marker.
//
// # Overview
//
// examples/components/kustomizeconfig/kustomizeconfig.yaml teaches kustomize
// how to rewrite cross-object name references (e.g. under a nameSuffix or
// nameReference transformer) between ORC objects, and between ORC objects and
// core Secrets. It is generated by cmd/kustomizeconfig-generator from
// "+orc:kustomize:ref=<Kind>" markers on the API types.
//
// # What this linter checks
//
// The linter flags any field typed KubernetesNameRef, *KubernetesNameRef, or
// []KubernetesNameRef which does not carry a "+orc:kustomize:ref=<Kind>"
// marker naming the Kind it references.
//
// A missing marker produces no diff in the generated kustomizeconfig.yaml
// (the generator simply never learns about the field), so 'make
// verify-generated' alone cannot catch it. This linter closes that gap.
//
// # Examples
//
// Bad (will be flagged):
//
//	type ProjectResourceSpec struct {
//	    DomainRef *KubernetesNameRef `json:"domainRef,omitempty"`
//	}
//
// Good (correct pattern):
//
//	type ProjectResourceSpec struct {
//	    // +orc:kustomize:ref=Domain
//	    DomainRef *KubernetesNameRef `json:"domainRef,omitempty"`
//	}
//
// # Status structs are exempt
//
// Fields declared on a struct whose name contains "Status" are exempt, as
// they are server-observed and not subject to kustomize name substitution.
//
// See https://k-orc.cloud/development/api-design/ for more details.
package kustomizeref
