/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/k-orc/openstack-resource-controller/api/v1alpha1"
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/pkg/clients/applyconfiguration/api/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRouters implements RouterInterface
type FakeRouters struct {
	Fake *FakeOpenstackV1alpha1
	ns   string
}

var routersResource = v1alpha1.SchemeGroupVersion.WithResource("routers")

var routersKind = v1alpha1.SchemeGroupVersion.WithKind("Router")

// Get takes name of the router, and returns the corresponding router object, and an error if there is any.
func (c *FakeRouters) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Router, err error) {
	emptyResult := &v1alpha1.Router{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(routersResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Router), err
}

// List takes label and field selectors, and returns the list of Routers that match those selectors.
func (c *FakeRouters) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RouterList, err error) {
	emptyResult := &v1alpha1.RouterList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(routersResource, routersKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RouterList{ListMeta: obj.(*v1alpha1.RouterList).ListMeta}
	for _, item := range obj.(*v1alpha1.RouterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested routers.
func (c *FakeRouters) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(routersResource, c.ns, opts))

}

// Create takes the representation of a router and creates it.  Returns the server's representation of the router, and an error, if there is any.
func (c *FakeRouters) Create(ctx context.Context, router *v1alpha1.Router, opts v1.CreateOptions) (result *v1alpha1.Router, err error) {
	emptyResult := &v1alpha1.Router{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(routersResource, c.ns, router, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Router), err
}

// Update takes the representation of a router and updates it. Returns the server's representation of the router, and an error, if there is any.
func (c *FakeRouters) Update(ctx context.Context, router *v1alpha1.Router, opts v1.UpdateOptions) (result *v1alpha1.Router, err error) {
	emptyResult := &v1alpha1.Router{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(routersResource, c.ns, router, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Router), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRouters) UpdateStatus(ctx context.Context, router *v1alpha1.Router, opts v1.UpdateOptions) (result *v1alpha1.Router, err error) {
	emptyResult := &v1alpha1.Router{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(routersResource, "status", c.ns, router, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Router), err
}

// Delete takes name of the router and deletes it. Returns an error if one occurs.
func (c *FakeRouters) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(routersResource, c.ns, name, opts), &v1alpha1.Router{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRouters) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(routersResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RouterList{})
	return err
}

// Patch applies the patch and returns the patched router.
func (c *FakeRouters) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Router, err error) {
	emptyResult := &v1alpha1.Router{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(routersResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Router), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied router.
func (c *FakeRouters) Apply(ctx context.Context, router *apiv1alpha1.RouterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Router, err error) {
	if router == nil {
		return nil, fmt.Errorf("router provided to Apply must not be nil")
	}
	data, err := json.Marshal(router)
	if err != nil {
		return nil, err
	}
	name := router.Name
	if name == nil {
		return nil, fmt.Errorf("router.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.Router{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(routersResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Router), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeRouters) ApplyStatus(ctx context.Context, router *apiv1alpha1.RouterApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.Router, err error) {
	if router == nil {
		return nil, fmt.Errorf("router provided to Apply must not be nil")
	}
	data, err := json.Marshal(router)
	if err != nil {
		return nil, err
	}
	name := router.Name
	if name == nil {
		return nil, fmt.Errorf("router.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.Router{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(routersResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.Router), err
}
