#!/usr/bin/env bash
# Copyright The ORC Authors.
#
# gen-helm.sh - generate Helm chart resources from controller-gen output.
# Run via "make generate" or "make generate-helm".
#
# CRDs: charts/orc-crds/crds is a symlink to config/crd/bases/, so no
#       copy needed.
#
# RBAC: copies the manager ClusterRole into charts/orc/templates/rbac/
#       with the name templated for Helm.
#
# Aggregation: copies the aggregating ClusterRoles generated into config/rbac/
#       by cmd/resource-generator into charts/orc-crds/templates/ with the name
#       and labels templated for Helm. They live in the CRD chart because they
#       only depend on the CRDs.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

RBAC_SRC="${REPO_ROOT}/config/rbac/role.yaml"
RBAC_DST="${REPO_ROOT}/charts/orc/templates/rbac/manager-clusterrole.yaml"
CRD_LINK="${REPO_ROOT}/charts/orc-crds/crds"

HEADER="# DO NOT EDIT - generated by hack/gen-helm.sh from config/rbac/role.yaml.
# Run 'make generate' to regenerate."

# --- Validate CRD symlink ---
if [ ! -d "${CRD_LINK}" ]; then
  echo "gen-helm: ERROR: CRD symlink ${CRD_LINK} is broken or missing (target: $(readlink "${CRD_LINK}" 2>/dev/null || echo 'N/A'))" >&2
  exit 1
fi

# --- Manager ClusterRole ---
echo "gen-helm: syncing manager ClusterRole → charts/orc/templates/rbac/manager-clusterrole.yaml"
mkdir -p "$(dirname "${RBAC_DST}")"
{
  echo "${HEADER}"
  # Prefix the ClusterRole name so it doesn't collide with bare kustomize
  # installs and matches the naming convention of the other chart RBAC
  # resources (which use the Helm fullname helper, defaulting to "orc-…").
  # Also inject standard Helm labels under metadata: for consistency with
  # the rest of the chart.
  awk '
    /^  name: manager-role$/ {
      sub(/manager-role/, "{{ include \"orc.fullname\" . }}-manager-role")
      print
      print "  labels:"
      print "    {{- include \"orc.labels\" . | nindent 4 }}"
      next
    }
    { print }
  ' "${RBAC_SRC}"
} > "${RBAC_DST}"

# Verify the Helm template expression was injected (guards against
# controller-gen changing the source format).
if ! grep -q '{{ include "orc.fullname" . }}-manager-role' "${RBAC_DST}"; then
  echo "gen-helm: ERROR: name templating failed — expected Helm expression not found in ${RBAC_DST}" >&2
  exit 1
fi

# --- Aggregated view/edit/admin ClusterRoles ---
# The kustomize roles in config/rbac/aggregate_{view,edit}_role.yaml are
# generated by cmd/resource-generator (so new kinds are picked up there). Copy
# them into the CRD chart with the name and labels templated for Helm.
AGG_CHART_DIR="${REPO_ROOT}/charts/orc-crds/templates"

echo "gen-helm: syncing aggregated ClusterRoles → charts/orc-crds/templates"
for mode in view edit; do
  src="${REPO_ROOT}/config/rbac/aggregate_${mode}_role.yaml"
  dst="${AGG_CHART_DIR}/aggregate-${mode}-clusterrole.yaml"
  {
    echo "# DO NOT EDIT - generated by hack/gen-helm.sh from config/rbac/aggregate_${mode}_role.yaml."
    echo "# Run 'make generate' to regenerate."
    echo "{{- if .Values.rbac.aggregate.enabled }}"
    echo "---"
    awk -v mode="${mode}" '
      /^#/ { next }
      $0 == "  name: aggregate-" mode "-role" {
        print "  name: {{ include \"orc-crds.fullname\" . }}-aggregate-" mode
        next
      }
      /^    app\.kubernetes\.io\/name: orc$/ {
        print "    {{- include \"orc-crds.labels\" . | nindent 4 }}"
        next
      }
      /^    app\.kubernetes\.io\/managed-by: kustomize$/ { next }
      { print }
    ' "${src}"
    echo "{{- end }}"
  } > "${dst}"

  # Verify the Helm template expressions were injected (guards against
  # the generated roles changing format).
  if ! grep -q '{{ include "orc-crds.fullname" . }}-aggregate-'"${mode}" "${dst}"; then
    echo "gen-helm: ERROR: name templating failed for aggregate-${mode}" >&2
    exit 1
  fi
  if ! grep -q '{{- include "orc-crds.labels" . | nindent 4 }}' "${dst}"; then
    echo "gen-helm: ERROR: label templating failed for aggregate-${mode}" >&2
    exit 1
  fi
done

echo "gen-helm: done"
