apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Role
metadata:
  name: roleassignment-sample-role
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    name: roleassignment-sample-role
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Group
metadata:
  name: roleassignment-sample-group
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    name: roleassignment-sample-group
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Project
metadata:
  name: roleassignment-sample-project
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    name: roleassignment-sample-project
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: RoleAssignment
metadata:
  name: roleassignment-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    roleRef: roleassignment-sample-role
    groupRef: roleassignment-sample-group
    projectRef: roleassignment-sample-project
