---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: SwiftContainer
metadata:
  name: swiftcontainer-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    name: swiftcontainer-sample-name
