apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Volume
metadata:
  name: volume-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample volume
    size: 1
