---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: HostAggregate
metadata:
  name: hostaggregate-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    availabilityZone: sample-az1
