---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: DNSZone
metadata:
  name: dnszone-sample
spec:
  cloudCredentialsRef:
    # TODO(scaffolding): Use openstack-admin if the resource needs admin credentials to be created
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    name: sample.example.com.
    email: admin@example.com
    description: Sample DNSZone
    # TODO(scaffolding): Add all fields the resource supports
