---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Role
metadata:
  name: appcred-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource: {}
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: User
metadata:
  name: appcred-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: unmanaged
  import:
    filter:
      name: admin
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Service
metadata:
  name: appcred-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: unmanaged
  import:
    filter:
      type: "compute"
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: ApplicationCredential
metadata:
  name: appcred-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    description: Sample Application Credential
    userRef: appcred-sample
    unrestricted: true
    secretRef: kubernetes-secret
    roleRefs:
      - appcred-sample
    accessRules:
      - method: "GET"
        serviceRef: appcred-sample
        path: "/v2.1/servers"
    expiresAt: "2033-03-03T22:22:22Z"
