---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: DNSZone
metadata:
  name: dnszone-sample
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    name: example.com.
    email: hostmaster@example.com
    description: Sample DNSZone
    ttl: 3600
    type: PRIMARY
