---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Role
metadata:
  name: role-example
spec:
  cloudCredentialsRef:
    cloudName: devstack-admin
    secretName: openstack-clouds
  managementPolicy: managed
  resource:
    domainRef: role-example-20-nov

