apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Network
metadata:
  name: network
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    tags:
      - orc-test
