apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Subnet
metadata:
  name: subnet
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    networkRef: network
    tags:
      - orc-test
    ipVersion: 4
    cidr: 192.168.1.0/24
    routerRef: router
