{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orc.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "orc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.port }}
      protocol: TCP
      targetPort: metrics
  selector:
    {{- include "orc.selectorLabels" . | nindent 4 }}
{{- end }}
