---
# Server that boots from a volume instead of an image
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Server
metadata:
  name: server
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    # No imageRef - booting from volume
    bootVolume:
      volumeRef: boot-volume
    flavorRef: flavor
    ports:
    - portRef: port
