/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// AddressScopeLister helps list AddressScopes.
// All objects returned here must be treated as read-only.
type AddressScopeLister interface {
	// List lists all AddressScopes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.AddressScope, err error)
	// AddressScopes returns an object that can list and get AddressScopes.
	AddressScopes(namespace string) AddressScopeNamespaceLister
	AddressScopeListerExpansion
}

// addressScopeLister implements the AddressScopeLister interface.
type addressScopeLister struct {
	listers.ResourceIndexer[*apiv1alpha1.AddressScope]
}

// NewAddressScopeLister returns a new AddressScopeLister.
func NewAddressScopeLister(indexer cache.Indexer) AddressScopeLister {
	return &addressScopeLister{listers.New[*apiv1alpha1.AddressScope](indexer, apiv1alpha1.Resource("addressscope"))}
}

// AddressScopes returns an object that can list and get AddressScopes.
func (s *addressScopeLister) AddressScopes(namespace string) AddressScopeNamespaceLister {
	return addressScopeNamespaceLister{listers.NewNamespaced[*apiv1alpha1.AddressScope](s.ResourceIndexer, namespace)}
}

// AddressScopeNamespaceLister helps list and get AddressScopes.
// All objects returned here must be treated as read-only.
type AddressScopeNamespaceLister interface {
	// List lists all AddressScopes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.AddressScope, err error)
	// Get retrieves the AddressScope from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.AddressScope, error)
	AddressScopeNamespaceListerExpansion
}

// addressScopeNamespaceLister implements the AddressScopeNamespaceLister
// interface.
type addressScopeNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.AddressScope]
}
