/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// FlavorListerExpansion allows custom methods to be added to
// FlavorLister.
type FlavorListerExpansion interface{}

// FlavorNamespaceListerExpansion allows custom methods to be added to
// FlavorNamespaceLister.
type FlavorNamespaceListerExpansion interface{}

// ImageListerExpansion allows custom methods to be added to
// ImageLister.
type ImageListerExpansion interface{}

// ImageNamespaceListerExpansion allows custom methods to be added to
// ImageNamespaceLister.
type ImageNamespaceListerExpansion interface{}

// NetworkListerExpansion allows custom methods to be added to
// NetworkLister.
type NetworkListerExpansion interface{}

// NetworkNamespaceListerExpansion allows custom methods to be added to
// NetworkNamespaceLister.
type NetworkNamespaceListerExpansion interface{}

// PortListerExpansion allows custom methods to be added to
// PortLister.
type PortListerExpansion interface{}

// PortNamespaceListerExpansion allows custom methods to be added to
// PortNamespaceLister.
type PortNamespaceListerExpansion interface{}

// RouterListerExpansion allows custom methods to be added to
// RouterLister.
type RouterListerExpansion interface{}

// RouterNamespaceListerExpansion allows custom methods to be added to
// RouterNamespaceLister.
type RouterNamespaceListerExpansion interface{}

// RouterInterfaceListerExpansion allows custom methods to be added to
// RouterInterfaceLister.
type RouterInterfaceListerExpansion interface{}

// RouterInterfaceNamespaceListerExpansion allows custom methods to be added to
// RouterInterfaceNamespaceLister.
type RouterInterfaceNamespaceListerExpansion interface{}

// SecurityGroupListerExpansion allows custom methods to be added to
// SecurityGroupLister.
type SecurityGroupListerExpansion interface{}

// SecurityGroupNamespaceListerExpansion allows custom methods to be added to
// SecurityGroupNamespaceLister.
type SecurityGroupNamespaceListerExpansion interface{}

// ServerListerExpansion allows custom methods to be added to
// ServerLister.
type ServerListerExpansion interface{}

// ServerNamespaceListerExpansion allows custom methods to be added to
// ServerNamespaceLister.
type ServerNamespaceListerExpansion interface{}

// SubnetListerExpansion allows custom methods to be added to
// SubnetLister.
type SubnetListerExpansion interface{}

// SubnetNamespaceListerExpansion allows custom methods to be added to
// SubnetNamespaceLister.
type SubnetNamespaceListerExpansion interface{}
