/*
Copyright 2025 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// KeyPairLister helps list KeyPairs.
// All objects returned here must be treated as read-only.
type KeyPairLister interface {
	// List lists all KeyPairs in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.KeyPair, err error)
	// KeyPairs returns an object that can list and get KeyPairs.
	KeyPairs(namespace string) KeyPairNamespaceLister
	KeyPairListerExpansion
}

// keyPairLister implements the KeyPairLister interface.
type keyPairLister struct {
	listers.ResourceIndexer[*apiv1alpha1.KeyPair]
}

// NewKeyPairLister returns a new KeyPairLister.
func NewKeyPairLister(indexer cache.Indexer) KeyPairLister {
	return &keyPairLister{listers.New[*apiv1alpha1.KeyPair](indexer, apiv1alpha1.Resource("keypair"))}
}

// KeyPairs returns an object that can list and get KeyPairs.
func (s *keyPairLister) KeyPairs(namespace string) KeyPairNamespaceLister {
	return keyPairNamespaceLister{listers.NewNamespaced[*apiv1alpha1.KeyPair](s.ResourceIndexer, namespace)}
}

// KeyPairNamespaceLister helps list and get KeyPairs.
// All objects returned here must be treated as read-only.
type KeyPairNamespaceLister interface {
	// List lists all KeyPairs in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.KeyPair, err error)
	// Get retrieves the KeyPair from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.KeyPair, error)
	KeyPairNamespaceListerExpansion
}

// keyPairNamespaceLister implements the KeyPairNamespaceLister
// interface.
type keyPairNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.KeyPair]
}
