/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// LBPoolLister helps list LBPools.
// All objects returned here must be treated as read-only.
type LBPoolLister interface {
	// List lists all LBPools in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.LBPool, err error)
	// LBPools returns an object that can list and get LBPools.
	LBPools(namespace string) LBPoolNamespaceLister
	LBPoolListerExpansion
}

// lBPoolLister implements the LBPoolLister interface.
type lBPoolLister struct {
	listers.ResourceIndexer[*apiv1alpha1.LBPool]
}

// NewLBPoolLister returns a new LBPoolLister.
func NewLBPoolLister(indexer cache.Indexer) LBPoolLister {
	return &lBPoolLister{listers.New[*apiv1alpha1.LBPool](indexer, apiv1alpha1.Resource("lbpool"))}
}

// LBPools returns an object that can list and get LBPools.
func (s *lBPoolLister) LBPools(namespace string) LBPoolNamespaceLister {
	return lBPoolNamespaceLister{listers.NewNamespaced[*apiv1alpha1.LBPool](s.ResourceIndexer, namespace)}
}

// LBPoolNamespaceLister helps list and get LBPools.
// All objects returned here must be treated as read-only.
type LBPoolNamespaceLister interface {
	// List lists all LBPools in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.LBPool, err error)
	// Get retrieves the LBPool from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.LBPool, error)
	LBPoolNamespaceListerExpansion
}

// lBPoolNamespaceLister implements the LBPoolNamespaceLister
// interface.
type lBPoolNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.LBPool]
}
