/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/k-orc/openstack-resource-controller/api/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// PortLister helps list Ports.
// All objects returned here must be treated as read-only.
type PortLister interface {
	// List lists all Ports in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Port, err error)
	// Ports returns an object that can list and get Ports.
	Ports(namespace string) PortNamespaceLister
	PortListerExpansion
}

// portLister implements the PortLister interface.
type portLister struct {
	listers.ResourceIndexer[*v1alpha1.Port]
}

// NewPortLister returns a new PortLister.
func NewPortLister(indexer cache.Indexer) PortLister {
	return &portLister{listers.New[*v1alpha1.Port](indexer, v1alpha1.Resource("port"))}
}

// Ports returns an object that can list and get Ports.
func (s *portLister) Ports(namespace string) PortNamespaceLister {
	return portNamespaceLister{listers.NewNamespaced[*v1alpha1.Port](s.ResourceIndexer, namespace)}
}

// PortNamespaceLister helps list and get Ports.
// All objects returned here must be treated as read-only.
type PortNamespaceLister interface {
	// List lists all Ports in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Port, err error)
	// Get retrieves the Port from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Port, error)
	PortNamespaceListerExpansion
}

// portNamespaceLister implements the PortNamespaceLister
// interface.
type portNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.Port]
}
