/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// QosPolicyLister helps list QosPolicies.
// All objects returned here must be treated as read-only.
type QosPolicyLister interface {
	// List lists all QosPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.QosPolicy, err error)
	// QosPolicies returns an object that can list and get QosPolicies.
	QosPolicies(namespace string) QosPolicyNamespaceLister
	QosPolicyListerExpansion
}

// qosPolicyLister implements the QosPolicyLister interface.
type qosPolicyLister struct {
	listers.ResourceIndexer[*apiv1alpha1.QosPolicy]
}

// NewQosPolicyLister returns a new QosPolicyLister.
func NewQosPolicyLister(indexer cache.Indexer) QosPolicyLister {
	return &qosPolicyLister{listers.New[*apiv1alpha1.QosPolicy](indexer, apiv1alpha1.Resource("qospolicy"))}
}

// QosPolicies returns an object that can list and get QosPolicies.
func (s *qosPolicyLister) QosPolicies(namespace string) QosPolicyNamespaceLister {
	return qosPolicyNamespaceLister{listers.NewNamespaced[*apiv1alpha1.QosPolicy](s.ResourceIndexer, namespace)}
}

// QosPolicyNamespaceLister helps list and get QosPolicies.
// All objects returned here must be treated as read-only.
type QosPolicyNamespaceLister interface {
	// List lists all QosPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.QosPolicy, err error)
	// Get retrieves the QosPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.QosPolicy, error)
	QosPolicyNamespaceListerExpansion
}

// qosPolicyNamespaceLister implements the QosPolicyNamespaceLister
// interface.
type qosPolicyNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.QosPolicy]
}
