/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v3/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RecordSetLister helps list RecordSets.
// All objects returned here must be treated as read-only.
type RecordSetLister interface {
	// List lists all RecordSets in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RecordSet, err error)
	// RecordSets returns an object that can list and get RecordSets.
	RecordSets(namespace string) RecordSetNamespaceLister
	RecordSetListerExpansion
}

// recordSetLister implements the RecordSetLister interface.
type recordSetLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RecordSet]
}

// NewRecordSetLister returns a new RecordSetLister.
func NewRecordSetLister(indexer cache.Indexer) RecordSetLister {
	return &recordSetLister{listers.New[*apiv1alpha1.RecordSet](indexer, apiv1alpha1.Resource("recordset"))}
}

// RecordSets returns an object that can list and get RecordSets.
func (s *recordSetLister) RecordSets(namespace string) RecordSetNamespaceLister {
	return recordSetNamespaceLister{listers.NewNamespaced[*apiv1alpha1.RecordSet](s.ResourceIndexer, namespace)}
}

// RecordSetNamespaceLister helps list and get RecordSets.
// All objects returned here must be treated as read-only.
type RecordSetNamespaceLister interface {
	// List lists all RecordSets in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RecordSet, err error)
	// Get retrieves the RecordSet from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.RecordSet, error)
	RecordSetNamespaceListerExpansion
}

// recordSetNamespaceLister implements the RecordSetNamespaceLister
// interface.
type recordSetNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RecordSet]
}
