/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RegisteredLimitLister helps list RegisteredLimits.
// All objects returned here must be treated as read-only.
type RegisteredLimitLister interface {
	// List lists all RegisteredLimits in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RegisteredLimit, err error)
	// RegisteredLimits returns an object that can list and get RegisteredLimits.
	RegisteredLimits(namespace string) RegisteredLimitNamespaceLister
	RegisteredLimitListerExpansion
}

// registeredLimitLister implements the RegisteredLimitLister interface.
type registeredLimitLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RegisteredLimit]
}

// NewRegisteredLimitLister returns a new RegisteredLimitLister.
func NewRegisteredLimitLister(indexer cache.Indexer) RegisteredLimitLister {
	return &registeredLimitLister{listers.New[*apiv1alpha1.RegisteredLimit](indexer, apiv1alpha1.Resource("registeredlimit"))}
}

// RegisteredLimits returns an object that can list and get RegisteredLimits.
func (s *registeredLimitLister) RegisteredLimits(namespace string) RegisteredLimitNamespaceLister {
	return registeredLimitNamespaceLister{listers.NewNamespaced[*apiv1alpha1.RegisteredLimit](s.ResourceIndexer, namespace)}
}

// RegisteredLimitNamespaceLister helps list and get RegisteredLimits.
// All objects returned here must be treated as read-only.
type RegisteredLimitNamespaceLister interface {
	// List lists all RegisteredLimits in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RegisteredLimit, err error)
	// Get retrieves the RegisteredLimit from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.RegisteredLimit, error)
	RegisteredLimitNamespaceListerExpansion
}

// registeredLimitNamespaceLister implements the RegisteredLimitNamespaceLister
// interface.
type registeredLimitNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RegisteredLimit]
}
