/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// RoleAssignmentLister helps list RoleAssignments.
// All objects returned here must be treated as read-only.
type RoleAssignmentLister interface {
	// List lists all RoleAssignments in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RoleAssignment, err error)
	// RoleAssignments returns an object that can list and get RoleAssignments.
	RoleAssignments(namespace string) RoleAssignmentNamespaceLister
	RoleAssignmentListerExpansion
}

// roleAssignmentLister implements the RoleAssignmentLister interface.
type roleAssignmentLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RoleAssignment]
}

// NewRoleAssignmentLister returns a new RoleAssignmentLister.
func NewRoleAssignmentLister(indexer cache.Indexer) RoleAssignmentLister {
	return &roleAssignmentLister{listers.New[*apiv1alpha1.RoleAssignment](indexer, apiv1alpha1.Resource("roleassignment"))}
}

// RoleAssignments returns an object that can list and get RoleAssignments.
func (s *roleAssignmentLister) RoleAssignments(namespace string) RoleAssignmentNamespaceLister {
	return roleAssignmentNamespaceLister{listers.NewNamespaced[*apiv1alpha1.RoleAssignment](s.ResourceIndexer, namespace)}
}

// RoleAssignmentNamespaceLister helps list and get RoleAssignments.
// All objects returned here must be treated as read-only.
type RoleAssignmentNamespaceLister interface {
	// List lists all RoleAssignments in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.RoleAssignment, err error)
	// Get retrieves the RoleAssignment from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.RoleAssignment, error)
	RoleAssignmentNamespaceListerExpansion
}

// roleAssignmentNamespaceLister implements the RoleAssignmentNamespaceLister
// interface.
type roleAssignmentNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.RoleAssignment]
}
