/*
Copyright 2024 The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/k-orc/openstack-resource-controller/api/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// RouterInterfaceLister helps list RouterInterfaces.
// All objects returned here must be treated as read-only.
type RouterInterfaceLister interface {
	// List lists all RouterInterfaces in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RouterInterface, err error)
	// RouterInterfaces returns an object that can list and get RouterInterfaces.
	RouterInterfaces(namespace string) RouterInterfaceNamespaceLister
	RouterInterfaceListerExpansion
}

// routerInterfaceLister implements the RouterInterfaceLister interface.
type routerInterfaceLister struct {
	listers.ResourceIndexer[*v1alpha1.RouterInterface]
}

// NewRouterInterfaceLister returns a new RouterInterfaceLister.
func NewRouterInterfaceLister(indexer cache.Indexer) RouterInterfaceLister {
	return &routerInterfaceLister{listers.New[*v1alpha1.RouterInterface](indexer, v1alpha1.Resource("routerinterface"))}
}

// RouterInterfaces returns an object that can list and get RouterInterfaces.
func (s *routerInterfaceLister) RouterInterfaces(namespace string) RouterInterfaceNamespaceLister {
	return routerInterfaceNamespaceLister{listers.NewNamespaced[*v1alpha1.RouterInterface](s.ResourceIndexer, namespace)}
}

// RouterInterfaceNamespaceLister helps list and get RouterInterfaces.
// All objects returned here must be treated as read-only.
type RouterInterfaceNamespaceLister interface {
	// List lists all RouterInterfaces in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.RouterInterface, err error)
	// Get retrieves the RouterInterface from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.RouterInterface, error)
	RouterInterfaceNamespaceListerExpansion
}

// routerInterfaceNamespaceLister implements the RouterInterfaceNamespaceLister
// interface.
type routerInterfaceNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.RouterInterface]
}
