/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// ShareTypeLister helps list ShareTypes.
// All objects returned here must be treated as read-only.
type ShareTypeLister interface {
	// List lists all ShareTypes in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ShareType, err error)
	// ShareTypes returns an object that can list and get ShareTypes.
	ShareTypes(namespace string) ShareTypeNamespaceLister
	ShareTypeListerExpansion
}

// shareTypeLister implements the ShareTypeLister interface.
type shareTypeLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ShareType]
}

// NewShareTypeLister returns a new ShareTypeLister.
func NewShareTypeLister(indexer cache.Indexer) ShareTypeLister {
	return &shareTypeLister{listers.New[*apiv1alpha1.ShareType](indexer, apiv1alpha1.Resource("sharetype"))}
}

// ShareTypes returns an object that can list and get ShareTypes.
func (s *shareTypeLister) ShareTypes(namespace string) ShareTypeNamespaceLister {
	return shareTypeNamespaceLister{listers.NewNamespaced[*apiv1alpha1.ShareType](s.ResourceIndexer, namespace)}
}

// ShareTypeNamespaceLister helps list and get ShareTypes.
// All objects returned here must be treated as read-only.
type ShareTypeNamespaceLister interface {
	// List lists all ShareTypes in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.ShareType, err error)
	// Get retrieves the ShareType from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.ShareType, error)
	ShareTypeNamespaceListerExpansion
}

// shareTypeNamespaceLister implements the ShareTypeNamespaceLister
// interface.
type shareTypeNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.ShareType]
}
