/*
Copyright The ORC Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/k-orc/openstack-resource-controller/v2/api/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// SwiftContainerLister helps list SwiftContainers.
// All objects returned here must be treated as read-only.
type SwiftContainerLister interface {
	// List lists all SwiftContainers in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.SwiftContainer, err error)
	// SwiftContainers returns an object that can list and get SwiftContainers.
	SwiftContainers(namespace string) SwiftContainerNamespaceLister
	SwiftContainerListerExpansion
}

// swiftContainerLister implements the SwiftContainerLister interface.
type swiftContainerLister struct {
	listers.ResourceIndexer[*apiv1alpha1.SwiftContainer]
}

// NewSwiftContainerLister returns a new SwiftContainerLister.
func NewSwiftContainerLister(indexer cache.Indexer) SwiftContainerLister {
	return &swiftContainerLister{listers.New[*apiv1alpha1.SwiftContainer](indexer, apiv1alpha1.Resource("swiftcontainer"))}
}

// SwiftContainers returns an object that can list and get SwiftContainers.
func (s *swiftContainerLister) SwiftContainers(namespace string) SwiftContainerNamespaceLister {
	return swiftContainerNamespaceLister{listers.NewNamespaced[*apiv1alpha1.SwiftContainer](s.ResourceIndexer, namespace)}
}

// SwiftContainerNamespaceLister helps list and get SwiftContainers.
// All objects returned here must be treated as read-only.
type SwiftContainerNamespaceLister interface {
	// List lists all SwiftContainers in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*apiv1alpha1.SwiftContainer, err error)
	// Get retrieves the SwiftContainer from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*apiv1alpha1.SwiftContainer, error)
	SwiftContainerNamespaceListerExpansion
}

// swiftContainerNamespaceLister implements the SwiftContainerNamespaceLister
// interface.
type swiftContainerNamespaceLister struct {
	listers.ResourceIndexer[*apiv1alpha1.SwiftContainer]
}
