---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: User
metadata:
  name: user-import-error
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: openstack-clouds
  managementPolicy: unmanaged
  import:
    filter:
      description: User from "import error" test
