name: Pull Request backporting

on:
  pull_request_target:
    types:
      - closed
      - labeled
permissions:
  contents: read
  pull-requests: write

jobs:
  backport_v1_0:
    name: "Backport to v1.0"
    # Only react to merged PRs for security reasons.
    # See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
          && contains(github.event.pull_request.labels.*.name, 'backport-v1.0')
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport-v1.0')
        )
      )
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token from the orc-backport-bot github-app
        id: generate_token
        uses: getsentry/action-github-app-token@a0061014b82a6a5d6aeeb3b824aced47e3c3a7ef
        with:
          app_id: ${{ secrets.BACKPORT_APP_ID }}
          private_key: ${{ secrets.BACKPORT_APP_PRIVATE_KEY }}

      - name: Backporting
        if: >
          contains(github.event.pull_request.labels.*.name, 'semver:patch')
          || contains(github.event.label.name, 'semver:patch')
        uses: kiegroup/git-backporting@7d895d030f5cf02f4a76c7f0bc79b41d8747b17c
        with:
          target-branch: release-1.0
          pull-request: ${{ github.event.pull_request.url }}
          auth: ${{ steps.generate_token.outputs.token }}
          no-squash: true
          strategy-option: find-renames

      - name: Report failure
        if: failure()
        run: gh issue comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BODY: >
            Failed to backport PR to `release-1.0` branch. See [logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

      - name: Report an error if backport unsupported labels
        if: >
          contains(github.event.pull_request.labels.*.name, 'semver:major')
          || contains(github.event.pull_request.labels.*.name, 'semver:minor')
          || contains(github.event.label.name, 'semver:major')
          || contains(github.event.label.name, 'semver:minor')
        run: gh pr comment "$NUMBER" --body "$BODY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.pull_request.number }}
          BODY: >
            Labels `semver:major` and `semver:minor` block backports to the branch `release-1.0`.
