name: container image

on:
  push:
    branches:
    - release-1.0

permissions:
  contents: read

env:
  image_tag_branch: quay.io/orc/openstack-resource-controller:branch-${GITHUB_REF_NAME}
  image_tag_commit: quay.io/orc/openstack-resource-controller:commit-${GITHUB_SHA::7}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - run: |
        docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_TOKEN }}" quay.io

        docker build -t ${{ env.image_tag_branch }} .
        docker push ${{ env.image_tag_branch }}

        docker build -t ${{ env.image_tag_commit }} --label quay.expires-after=4w .
        docker push ${{ env.image_tag_commit }}
