on:
  push:
    branches:
    - release-2.0
  merge_group:
  pull_request:
name: generate
permissions:
  contents: read

jobs:
  make-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # tag=v7.0.0
        with:
          persist-credentials: false

      - run: |
          make generate
          git diff --exit-code

      - run: sudo apt-get install -y libgpgme-dev

      - run: |
          make generate-bundle
          git diff --exit-code
