on:
  push:
    branches:
    - release-2.0
  merge_group:
  pull_request:
name: generate
permissions:
  contents: read

jobs:
  make-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # tag=v6.0.3
        with:
          persist-credentials: false

      - run: |
          make generate
          git diff --exit-code

      - run: sudo apt-get install -y libgpgme-dev

      - run: |
          make generate-bundle
          git diff --exit-code
