on:
  push:
    branches:
    - release-2.0
  merge_group:
  pull_request:
name: generate
permissions:
  contents: read

jobs:
  make-generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # tag=v7.0.1
        with:
          persist-credentials: false

      - run: |
          make generate
          git diff --exit-code

      - run: sudo apt-get install -y libgpgme-dev

      - run: |
          make generate-bundle
          git diff --exit-code
